#=================================================================
# Portal Pipeline Server DAT::USC_Map Messages
#
# Number Range: 35201-35300
#----------------------------------------------------------------
# Note: Add only numbers inside the allocated range.
#       Do not change existing numbers.
#=================================================================

#Warnings
WRN_NO_USC_MAP_ENTRY_FOR ZONE_MODEL  | DAT::USC_Map::No Usc Entries found for zone model ID (%s)                   | 35202
WRN_NO_USC_ENTRY_FOR_PATTERN         | DAT_USC_Map_ZoneModel::No usc-entries found during pattern matching         | 35203
WRN_INVALID_QTY_VAL                  | DAT_USC_Map_ZoneModel::Invalid quantity value for entry (%s)                | 35204       
WRN_INVALID_TIME_FRAME               | DAT_USC_Map_ZoneModel::Invalid timeframe for entry (%s)                     | 35205
WRN_NO_VALID_USC_ENTRY               | DAT_USC_Map_ZoneModel::No Valid USC entry mapping found                     | 35206
WRN_NO_USC_ENTRY_FOR_PATTERN_AND_SD  | DAT_USC_Map_ZoneModel::Pattern Matching - no usc-entries found for SD (%s)  | 35207
WRN_INVALID_PATH_NUM_FOR_SD          | DAT_USC_Map_ZoneModel::Pattern Matching - invalid path number for SD (%s)   | 35208
WRN_INVALID_BITVEC_MATCH_FOR_SD      | DAT_USC_Map_ZoneModel::Pattern Matching - bitVec match error for SD (%s)    | 35209
ERR_FSM_ENGINE_FAILED                | DAT_USC_Map_ZoneModel::FSM Engine Failed for zonemodel (%s)                 | 35210
ERR_USC_ENTRY_INVALID                | DAT_USC_Map::Invalid USC Entry (%s)                                         | 35211
