#=================================================================
# Portal Pipeline Server DAT::Recycle Messages
#
# Number Range: 31401-31500
#----------------------------------------------------------------
# Note: Add only numbers inside the allocated range.
#       Do not change existing numbers.
#=================================================================

ERR_QUEUE_FILE_NOT_OPENED          | Error opening or creating queue file %s.                       | 31401 
ERR_QUEUE_FILE_READ            | Error reading queue file %s.    | 31402 
ERR_QUEUE_FILE_WRITE            | Error writing queue file %s.        | 31403 
