#
# Normal/Info messages.
#
INF_NETWORK_OPERATOR_TABLE_LOADED   | %s Network Operators loaded into memory.                           | 31501
INF_SWITCH_TABLE_LOADED             | Switches for %s network models loaded into memory.                 | 31502 
INF_POI_TABLE_LOADED                | POIs for %s network models loaded into memory.                     | 31503
INF_TRUNK_TABLE_LOADED              | Trunks for %s network models loaded into memory.                   | 31504
INF_TRUNK_CNF_TABLE_LOADED          | TrunksCnf entries for %s network models loaded into memory.        | 31505
INF_NETWORK_MODEL_LOADED            | Network model '%s' loaded into memory.                             | 31506
INF_ICPRODUCT_TABLE_LOADED          | %s IcProducts loaded into memory.                                  | 31507
INF_ICPRODUCT_CNF_TABLE_LOADED      | IcProduct config-entries for %s network models loaded into memory. | 31508
INF_POIAREA_TABLE_LOADED            | Areacodes for reseller rating loaded.                              | 31509
INF_CIBER_OCC_TABLE_LOADED          | %s CiBER OCC objects loaded into memory.                           | 31510

#
# Warnings.
#

#
# Errors.
#
ERR_LOADING_NETWORK_OPERATOR        | Loading IFW_NETWORK_OPERATOR failed (%s).                      | 31511 
ERR_LOADING_NETWORK_MODEL           | Loading IFW_NETWORKMODEL failed (%s).                          | 31512
ERR_LOADING_POI                     | Loading IFW_POI failed (%s).                                   | 31513
ERR_LOADING_SWITCH                  | Loading IFW_SWITCH failed (%s).                                | 31514
ERR_LOADING_TRUNK                   | Loading IFW_TRUNK failed (%s).                                 | 31515
ERR_LOADING_TRUNK_CNF               | Loading IFW_TRUNK_CNF failed (%s).                             | 31516
ERR_LOADING_ICPRODUCT               | Loading IFW_ICPRODUCT failed (%s).                             | 31517
ERR_LOADING_ICPRODUCT_CNF           | Loading IFW_ICPRODUCT_CNF failed (%s).                         | 31518
ERR_LOADING_CIBER_OCC               | Loading IFW_CIBER_OCC failed (%s).                             | 31519
ERR_SETUP_ICPRODUCT_CNF_ENTRY       | Error while setting up IFW_ICPRODUCT_CNF table from database. Reason: %s.  | 31520

#
# Eror messages from getCiberOccForSourceNetwork()
#
ERR_GETTING_NETWORK_MODEL           | Unknown network model: %s.              | 31521
ERR_GETTING_PRODUCT_GROUP           | Could not get product group for %s.     | 31522
ERR_GETTING_NETWORK_OPERATOR        | Could not get network operator for %s.  | 31523
ERR_GETTING_CIBER_OCC               | %s                                      | 31524
