ERR_ATTACH_DAT_DISCOUNT                 | Could not attach the account balance manager as '%s' to DAT_DiscountPlugIn.   | 30900
ERR_DAT_DSC_GENERIC                     | FATAL ERROR '%s' line '%s' msg '%s' detail '%s'.         | 30814
ERR_DETERMINE_STEP                      | Could not determine the step of related resource id: '%s'.    | 30901
ERR_DISCOUNT_DUPLICATE                  | Cannot insert new discount model '%s'.        | 30801
ERR_DSCMISSING_DEF                      | '%s'                                          | 30803
ERR_DSCTIMEFRAME_DEF                    | '%s'                                          | 30802
ERR_EVENT_REGISTERED                    | Event '%s' could not be registered to DAT_Listener.   | 30817
ERR_ISCRIPT_VALIDATION_FAILED           | IScript validation failed. '%s'.              | 30928
ERR_REGEXP                              | Invalid regular expression '%s'.              | 30804
ERR_THRESHOLDTO_SET_TO_MAX              | Discount Step Threshold_To value: %s is inappropriate, setting it to maximum: %s"     | 30925
ERR_DSC_EXCLUSION_REG_SETTING           | Error in discount exclusion registry setting  | 30938 
INF_CONTRIB_BEGIN                       | Loading event contributor map started.        | 30929
INF_CONTRIB_END                         | Loading event contributor map finished.       | 30930
INF_DSC_DISCOUNTS_BEGIN                 | Start loading discount objects from database.         | 30931
INF_DSC_DISCOUNTS_END                   | Loading of discount objects finished.         | 30932
INF_DSC_FILTER_BEGIN                    | Start loading discount model filter from database.    | 30807
INF_DSC_FILTER_END                      | Loading of discount model filter finished.    | 30808
INF_DSC_MODEL_BEGIN                     | Start loading discount models from database.  | 30805
INF_DSC_MODEL_END                       | Loading of discount models finished.          | 30806
INF_DSC_NOT_NEEDED                      | No discount models loaded.                    | 30811
INF_DSC_RULES_BEGIN                     | Start loading discount rules from database.   | 30809
INF_DSC_RULES_END                       | Loading of discount rules finished.           | 30810
INF_DSC_SPONSORS_BEGIN                  | Start loading sponsorship objects from database.      | 30933
INF_DSC_SPONSORS_END                    | Loading of sponsorship objects finished.      | 30934
INF_DSC_TRG_BEGIN                       | Start loading discount trigger and conditions.        | 30812
INF_DSC_TRG_END                         | Loading of discount trigger and conditions finished.  | 30813
INF_RELOAD_DEMANDED                     | Reload of discount configuration demanded.    | 30842
INF_RELOAD_SUCCESSFUL                   | Discount pricing data reloaded sucessfully.   | 30941
INF_RELOAD_EVAL_SCRIPTS_DEMANDED        | Reload of discount Eval Scripts demanded.     | 30843
INF_RELOAD_EVAL_SCRIPTS_SUCCESSFUL      | Reload of discount Eval Scripts completed.    | 30844
INF_DEPENDENCY_BEGIN                    | Start loading mutually exclusive discount objects.  | 30935
INF_DEPENDENCY_END                      | Loading of mutually exclusive discount objects finished.  | 30936  
WRN_WRONGVALUE_SET_TO_REGPARAM          | Unexpected value set for registry parameter %s. | 30937
ERR_RELOAD_FAILURE                      | Reloading discount pricing data failed. | 30939
ERR_RELOAD_EXTDATA_FAILURE              | Re-Init of data in Discount Fuctional PlugIn or Balance Data PlugIn Failed. | 30940
ERR_DB_CONNECT                          | Database connection is invalid. Possible solution is to restart DB & send reconnect singnal. Error: %s,  | 30942
ERR_RELOAD_EVAL_SCRIPTS_FAILED          | Reload of discount Eval Scripts failed. | 30943
