ERR_ACCRT_MESSAGE                       | Error message for DAT_AccountRealtime plugin module: '%s'     	| 31101
ERR_NOT_IMPLEMENTED                     | Method not implemented in DAT_AccountRealtime plugin module: '%s'     | 31102
INF_ACCRT_START                         | Starting DAT_AccountRealtime plugin module: '%s'      		| 31103
ERR_EXECUTING_OPCODE                    | Following error thrown during opcode execution '%s'.                  | 31104
