##################################################################
# DAT_NumberPortability error messages
##################################################################

INF_NUM_NPORT_LOADED                    | '%s' Number Portability record(s) loaded into the memory.         | 30201
INF_NUM_NPORT_RELOADED                  | '%s' Number Portability records(s) reloaded into the memory.       | 30202
INF_NUM_NPORT_ADDED                     | '%s' Number Portability records appended to the memory.          | 30203
ERR_CLOSE_NP_FILE                      | Error closing Number Portability data File '%s'.      | 30204
ERR_NUM_PORT_RELOAD                    | Error reloading data from the Number Portability data file '%s'. | 30205
INF_NUM_PORT_PRINT_DATA                | '%s' Number Portability record(s) printed on the '%s'. | 30206
INF_NP_THREAD_END                      | Thread ended '%s'. | 30207
INF_NP_THREAD_DIED                     | Thread died '%s'.| 30208
ERR_NUM_PORT_DELTALOAD                 | Error while appending additional Number Portability data from the file '%s'. | 30209
