#
# Normal/Info messages.
#
INF_NUMBER_RATEPLAN_LOADED              | %s rateplan(s) loaded successfully into memory.       | 30401

#
# Warnings.
#
WRN_LOADING_RATEPLAN                    | Rateplan '%s' is not loaded                           | 30405
WRN_LOADING_RATEPLAN_VERSION            | Version '%s' for rateplan '%s' is not loaded          | 30406

#
# Errors.
#

ERR_INVALID_RUM_IN_RUMGROUP             | Found rum group(s) in IFW_RUMGROUP with no entry in IFW_RUMGROUPS_LNK ("%s").         | 30402
ERR_INVALID_RUM_IN_SERVICE              | Found rum group(s) in IFW_SERVICE with no entry in IFW_RUMGROUP ("%s").       | 30403
ERR_INVALID_SPLITTING_TYPE              | IFW_RATEPLAN.SPLITTING has invalid value '%s'. Possible values are '0', '1', '2', '3'.        | 30404
