ERR_INVALID_ITEM_POID_LIST          | Item Poid List from DAT_Account is invalid(%s)           | 35101
ERR_NO_TYPE_FOUND_FOR_TAG           | No matching type found for given item tag                | 35102
ERR_FAILED_TO_RESERVE_POID_IDS      | Failed to reserve the Poid Ids                           | 35103
ERR_FAILED_TO_GENERATE_MAP_TABLE    | Failed to generate Tag and Type map table                | 35104
ERR_SET_ITEM_POID_LIST_FAILED       | Failed to set Item Poid List                             | 35105
ERR_FSM_CREATION_FAILED             | Failed to get data from db or FSM creation failed(%s)    | 35106
ERR_NO_ITEM_TAG                     | Failed to get itemTag(%s)                                | 35107
ERR_NO_VALID_POID_ID_FOUND          | Invalid PoidId(%s)                                       | 35108
