INF_SCENARIO_LOADED                     | Scenario '%s' loaded.                         | 30501
ERR_INVALID_DATATYPE                    | Datatype %s is invalid.                       | 30502
ERR_INVALID_VALUE                       | Value '%s' is invalid.                        | 30503
ERR_INVALID_FUNCTION                    | Function %s is invalid.                       | 30504
ERR_INVALID_FLUSHMODE                   | Flushmode %s is invalid.                      | 30505
ERR_NO_CLASSITEMS                       | No classitems defined for class '%s'.         | 30506
ERR_DATATYPE_MISMATCH                   | Datatype for %s does not match value '%s'.    | 30507
ERR_GROUPING_NOT_FOUND                  | Grouping %s does not exist.                   | 30508
