ERR_FILE_ID_NOT_FOUND            | File ID Not Found | 40501
ERR_FILE_FORMAT_INCORRECT        | File Format is not correct | 40502
INF_DRP_CALL                     | Dropped Call Found | 40503
INF_CONTINUE_CALL                | Continuation Call Found | 40504
INF_DUP_DRP_CALL                 | Duplicated Dropped Call Found | 40505
WRN_FILE_NOT_FOUND               | Main data file not found. | 40506
ERR_REMOVING_FILE                | Could not remove file %s | 40507
ERR_INSERT_INTO_MAP_FAILED       | Insertion into the DroppedCallInfoMap failed  : %s |40508
ERR_RESTORE_FAILED               | Restore of the file failed | 40509
ERR_SERIALIZE_FAILED             | Serialize to the file faild | 40510
ERR_UNABLE_TO_RETRIEVE_XML_ID    | Unable to retrieve XML Id | 40511
ERR_VALUE_FROM_XML_ID            | Unable to retrieve the value from XML Id | 40512
INF_TEMP_NOT_FOUND               | Temp prefix not defined | 40513 
INF_SAME_BILL_CYCLE              | Same bill cycle configuration is selected | 40514  
INF_DRPD_CALL_REMOVED            | Map entry of a Dropped Call is removed : %s | 40515
INF_DROPPED_CALLS_REMOVED        | No. of Dropped Call entries removed by removelimit semaphore : %s | 40516
ERR_DROPPED_CALL_UPDATION_FAILED | Updation of Dropped Call entry in the memory map failed : %s | 40517
ERR_DATA_TYPE_MISMATCH           | Datatype of ContinuationCallField = '%s' does not match the datatype of DroppedCallField = '%s' | 40518
ERR_VALUE_PROFILE_ERA            | Invalid value of DROPPED_CALL Profile ERA '%s = %s'. Profile ERA '%s' is not set, So the default behavior is assumed.| 40519 
