#===============================================================================
# $Id: FCT_IScriptPlugIn_Error.msg,v 1.1 2000/09/08 15:02:43 sd Exp $
#
# $RCSfile: FCT_IScriptPlugIn_Error.msg,v $
# $Revision: 1.1 $
# $Author: sd $
# $Date: 2000/09/08 15:02:43 $
# $Locker:  $
#-------------------------------------------------------------------------------
# $Log: FCT_IScriptPlugIn_Error.msg,v $
# Revision 1.1  2000/09/08 15:02:43  sd
# - The iScripts are checked for usability now.
#
#===============================================================================

ERR_SCRIPT_NOT_USABLE             | The iScript `%s' is not usable.
