ERR_FCT_EO_EDR_ITERATOR                 | Could not reset '%s' iterator                 | 18901
ERR_FCT_EO_EDR_BLOCK_MISSING            | '%s' block missing in the EDR.                | 18902
ERR_FCT_EO_INVALID_ID                   | Invalid '%s' ID.                              | 18903
ERR_FCT_EO_FILE_OPEN_FAIL               | Failed to open file '%s' .                    | 18904
INF_FCT_EO_SKIP_PREV_BILLING_CYCLE      | The flag to skip previous billing cycle is set to "%s". | 18905
INF_FCT_EO_DISCOUNT_SHARING             | The flag to support discount sharing is set to "%s". | 18906
