ERR_DB_ROUTING_FAILED                   | Splitting failed (%s).                        | 15601
ERR_DATA_MODULE_IS_NOT_A_ROUTER         | Data Module (%s) is not configured as a Router.       | 15602
ERR_JOB_AMT_MIGRATION                   | Job is under migration state and being directed.      | 15603
ERR_REGISTRY_KEY_ERROR                  | Error found in registry key value pair (%s).          | 15604