ERR_RATEPLAN_NOT_A_NUMBER               | Rateplan-Id '%s' is not a number.             | 16601
ERR_RATEPLAN_TYPE_INV                   | Rateplan-Type '%s' does not match valid values ('R'   | 16602
ERR_RATEPLAN_VERSION_NOT_FOUND          | Rateplan-Version not found for Id (%s) and Date (%s).         | 16603
ERR_NO_RATEPLAN                         | No rateplan-code or -id defined in DETAL.ASS_CBD.CP.  | 16604
ERR_ZONE_VALUE_NOT_FOUND                | ZoneValue not found for ZM-Id=%s, Date=%s, SC=%s, A#=%s, B#=%s. | 16605
ERR_ASS_CBD_NOT_FOUND                   | No ASSOCIATED_CHARGE_BREAKDOWN block is found | 16606
