WRN_FIELD_NOT_FOUND                     | EDR field '%s' does not exist.                | 16201
INF_EDR_DISCARDED_INFO                  | EDR discarded by '%s'.                        | 16202
INF_EDR_SKIPPED_INFO                    | EDR skipped by '%s'.                          | 16203
INF_EDR_DISCARDED_COUNT                 | %s EDRs discarded.                            | 16204
INF_EDR_SKIPPED_COUNT                   | %s EDRs skipped.                              | 16205
