ERR_RATEPLAN_VERSION_ID_NOT_FOUND       | Rateplan-Version not found (IFW_RATEPLAN_VER) for Rateplan=%s and Version=%s. Packet no. '%s'.        | 16501
ERR_RATEPLAN_VERSION_DATE_NOT_FOUND     | Rateplan-Version not found (IFW_RATEPLAN_VER) for Rateplan=%s and Date=%s. Packet no. '%s'.   | 16502
ERR_TIMEMODEL_NOT_FOUND                 | Timemodel not found (IFW_RATEPLAN_CNF) for RP=%s, RPV=%s, IC=%s, SCode=%s and SClass=%s. Packet no. '%s'.     | 16503
ERR_RATE_PRICEMODEL_NOT_FOUND           | Pricemodel not found (IFW_RATEPLAN_CNF) for RP=%s, RPV=%s, IC=%s, SCode=%s, SClass=%s, TMM=%s and TZ=%s. Packet no. '%s'.     | 16504
ERR_TIMEZONE_NOT_FOUND                  | Timezone not found in TimeModel=%s for Date=%s. Packet no. '%s'.      | 16505
ERR_PRICEMODEL_NOT_FOUND                | Pricemodel '%s' not found. See process-log-file for invalid pricemodels not loaded. Packet no. '%s'.  | 16506
WRN_PRICEMODEL_RUM_NOT_FOUND            | Pricemodel-RUM not found for PM=%s, RES=%s and RUM=%s. Packet no. '%s'.       | 16507
ERR_PRICEMODEL_STEP_NOT_FOUND           | Pricemodel-Step not found for PM=%s, RES=%s RUM=%s. Packet no. '%s'.  | 16508
ERR_PRICEMODEL_CONFIG_NOT_FOUND         | Pricemodel-Config not found for PM=%s, RES=%s, RUM=%s, Step=%s, Frame=%s and Date=%s.         | 16509
ERR_INVALID_ADDON_TYPE                  | Addon-Type in IFW_RATEPLAN_CNF for RP=%s, RP-V=%s, IC=%s, SCode=%s, SClass=%s, TM=%s and TZ=%s is invalid. Not in 'P'ercentage, 'A'bsolute or 'N'ew value.    | 16510
ERR_RUM_GROUP_NOT_FOUND                 | Found no valid rum group for packet no. '%s'.         | 16511
ERR_RUM_QUANTITY_INDEX_NOT_FOUND        | RUM quantity index not found for RUM '%s'.         | 16512
ERR_UOM_QUANTITY_INDEX_NOT_FOUND        | UOM quantity index not found for RUM '%s'.         | 16513

