#=================================================================
# Portal Pipeline Server FCT::Suspense Messages
#
# Number Range: 15301-15400
#----------------------------------------------------------------
# Note: Add only numbers inside the allocated range.
#       Do not change existing numbers.
#=================================================================
# 03-Oct-2003: Initial version
#=================================================================

ERR_NO_DEFAULT_SUSPENSE_REASON   | No default suspense reason and subreason specified.            | 15301
ERR_ASS_SUSPENSE_EXT_MISSING     | No ASS_SUSPENSE_EXT data block. FCT_PreSuspense is not active. | 15302
ERR_REJECT_STREAM_ERROR          | RejectStream registry must be set to "%s".                     | 15303
WRN_FIELD_MAP_NOT_FOUND		 | Registry entry '%s' not found.				  | 15304
ERR_EFENTRY_INVALID 		 | Failed to setup suspense mapping entry (%s)			  | 15305
ERR_NO_MATCHING_ENTRY_IN_EDR_FLD_MAP   | No matching entry found in suspense edr field map table  | 15306
