#=================================================================
# Portal Pipeline Server FCT::PreSuspense Messages
#
# Number Range: 15201-15300
#----------------------------------------------------------------
# Note: Add only numbers inside the allocated range.
#       Do not change existing numbers.
#=================================================================
# 03-Oct-2003: Initial version
#=================================================================

ERR_DATATYPE_NOT_SUPPORTED    | Datatype EDR::FieldDescr::%s is not supported. | 15201
ERR_NO_QUERYABLE_FIELDS_TABLE | No queryable fields specified in registry.     | 15202
WRN_NO_QUERYABLE_FIELDS       | No queryable fields specified for table %s.    | 15203

