##################################################################
# $Id: FCT_RateAdjust_Error.msg,v 1.1 2001/06/28 14:00:07 sd Exp $
#
# FCT_RateAdjust error messages
##################################################################

INF_RATEADJUST_MAP_LOADED               | Rate adjust map loaded (%s).                  | 16701
INF_READING_RATEADJUST                  | Reading rate adjust map from file %s.         | 16702
ERR_ADD_RATEADJUST                      | Failure while adding rate adjust entry (%s).  | 16703
