ERR_CUSTOMER_NOT_FOUND                  | No customer datablock found.                  | 16101
WRN_CUSTOMER_NOT_FOUND                  | No customer datablock found. Using Default-Rateplan '%s' to continue.         | 16102
ERR_RATEPLAN_NOT_DEFINED                | No rateplan defined for customer account '%s'.        | 16103
ERR_INIT_SLA_TABLE                      | Error during initialisation from IFW_SLA table. See pipeline log for additional information.  | 16104
