INF_SCENARIO_STARTED                    | Started processing scenario '%s'.             | 15701
INF_AGGREGATIONS_WRITTEN                | %s aggregations written to file '%s'.         | 15702
INF_FILE_CREATED                        | File '%s' created.                            | 15703
INF_FILE_REMOVED                        | File '%s' removed.                            | 15704
WRN_NO_SCENARIOS_CONFIGURED             | No scenarios configured.                      | 15705
WRN_SCENARIO_NOT_ACTIVE                 | Scenario '%s' is not active.                  | 15706
ERR_NO_DEPENDENT_CLASS_DEFINED          | No dependent class defined for class '%s' and classitem '%s'  | 15707
ERR_SCENARIO_NOT_DEFINED                | Scenario '%s' not defined.                    | 15708
ERR_DATABLOCK_NOT_FOUND                 | EDR datablock '%s' not found.                 | 15709
ERR_EDR_ITERATOR_FAILURE                | EDR indexes mismatch: %s.                     | 15710
INF_CTLFILE_SUPPRESSED                  | Controle file '%s' set as not to create       | 15711
ERR_CTLFILE_NOT_CREATED                 | Control File '%s' could not be created. Reason : '%s'        | 15712
