#=================================================================
# Portal Pipeline Server FCT::BatchSuspense Messages
#
# Number Range: 18601-18700
#----------------------------------------------------------------
# Note: Add only numbers inside the allocated range.
#       Do not change existing numbers.
#=================================================================
# 10-Jan-2006: Initial version
#=================================================================

ERR_NO_DEFAULT_BATCH_SUSPENSE_REASON   | No default batch suspense reason.                              | 18601
ERR_INVALID_RESUBMIT_INFO   | Invalid resubmit info received for batch name '%s' and pipeline '%s'.     | 18602
ERR_NO_BATCH_SUSPENSE_REASON   | No batch suspense reason in /config/suspense_reason_code object.       | 18603
