#===============================================================================
# $Id: FCT_APN_Map_Error.msg,v 1.1 2001/09/18 11:39:35 dhatton Exp $
#
# $RCSfile: FCT_APN_Map_Error.msg,v $
# $Revision: 1.1 $
# $Author: dhatton $
# $Date: 2001/09/18 11:39:35 $
# $Locker:  $
#-------------------------------------------------------------------------------
# $Log: FCT_APN_Map_Error.msg,v $
# Revision 1.1  2001/09/18 11:39:35  dhatton
# Error messages!
#
#===============================================================================

ERR_INIT_APN_MAPTABLE                   | Initialise of map table failed (%s)           | 15801
ERR_INIT_EDR_ITERATOR_CHARGE_PACKET     | Failed to initialise charge packet iterator (%s).     | 15802
ERR_INIT_EDR_ITERATOR_ZONE_PACKET       | Failed to initialise zone packet iterator (%s).       | 15803
ERR_RAZ_MAP_NOT_USABLE                  | Run after zoning map table not usable (%s).   | 15804
ERR_RAZ_MAP_TABLE_NOT_INITIALISED       | Run after zoning map table not initialised (%s).      | 15805
ERR_GPRS_GSMW_AMBIGUITY                 | GPRS and GSMW extensions present. This is ambiguous. (%s).    | 15806
ERR_RBZ_MAP_TABLE_INVALID               | Run before zoning map table not usable (%s).  | 15807
ERR_RBZ_MAP_TABLE_NOT_INITIALISED       | Run before zoning map table not initialised (%s).     | 15808

