#===============================================================================
# $Id: FCT_UsageClassMap_Error.msg,v 1.3 2001/09/18 12:46:01 dhatton Exp $
#
# $RCSfile: FCT_UsageClassMap_Error.msg,v $
# $Revision: 1.3 $
# $Author: dhatton $
# $Date: 2001/09/18 12:46:01 $
# $Locker:  $
#-------------------------------------------------------------------------------
# $Log: FCT_UsageClassMap_Error.msg,v $
# Revision 1.3  2001/09/18 12:46:01  dhatton
# Initial checkin.
#
#===============================================================================
#Errors
ERR_UCENTRY_INVALID                     | Failed to setup usage class mapping entry (%s).       | 17301

#Warnings
 
#Info.
