#===============================================================================
# $Id: FCT_EnhancedSplitting_Error.msg,v 1.1 2000/04/10 13:48:15 sd Exp $
#
# $RCSfile: FCT_EnhancedSplitting_Error.msg,v $
# $Revision: 1.1 $
# $Author: sd $
# $Date: 2000/04/10 13:48:15 $
# $Locker:  $
#-------------------------------------------------------------------------------
# $Log: FCT_EnhancedSplitting_Error.msg,v $
# Revision 1.1  2000/04/10 13:48:15  sd
# - Initial revision.
#
#===============================================================================

# edr errors
ERR_NO_SPLITTING_ENTRY                  | No matching splitting rule found.             | 16401

# info messages
INF_INIT_SPLITTING_TABLE                | Loading splitting entries from %s.            | 16402
INF_SPLITTING_ENTRIES_LOADED            | %s splitting entries loaded.                  | 16403

# error messages
ERR_INSERT_SPECSYS                      | Failed to insert `%s=%s' into the mapping table.      | 16404
ERR_NO_STREAM_FOR_SPECSYS               | No output stream for specialist system `%s'.  | 16405
ERR_SETUP_SPLITTING_ENTRY               | Setup for splitting entry (%s) failed: %s.    | 16406
ERR_ADD_SPLITTING_PATTERNS              | Failed to add patterns to fsm (%s): %s.       | 16407
