#===============================================================================
# $Id: FCT_CliMapping_Error.msg,v 1.1 2001/09/18 12:05:13 dhatton Exp $
#
# $RCSfile: FCT_CliMapping_Error.msg,v $
# $Revision: 1.1 $
# $Author: dhatton $
# $Date: 2001/09/18 12:05:13 $
# $Locker:  $
#-------------------------------------------------------------------------------
# $Log: FCT_CliMapping_Error.msg,v $
# Revision 1.1  2001/09/18 12:05:13  dhatton
# Error messages!
#
#===============================================================================

#Error messages.
ERR_EDR_FACTORY                         | Error failed to get the edr factory (%s).     | 17901

#Warning messages.
WRN_CLIENTRY_INVALID                    | Setup cli Map entry failed (%s).              | 17902

#Info. messages.
INF_CLI_MAP_ENTRIES_LOADED              | %s cli mapping entries loaded.                | 17903
INF_READING_CLI                         | Reading cli mapping file (%s).                | 17904
