ERR_APPLYBAL_CANCEL_DEMANDED        | EDR belongs to a cancel demanded transaction.         | 18501
ERR_APPLYBAL_CANCEL_EDR             | EDR transaction cancel demanded.                      | 18502
ERR_APPLYBAL_EDR_ITERATOR           | Could not reset EDR iterator.                         | 18503
ERR_APPLYBAL_NO_ACCOUNT_BALANCE     | Could not create/find balance for BG/Resource: %s.    | 18504
ERR_APPLYBAL_PLUGIN_INVALID_STATE   | Required action does not fit to current state '%s'.   | 18505
ERR_APPLYBAL_ROLLBACK_EDR           | EDR transaction rollback demanded                     | 18506
INF_APPLYBAL_DEADLOCK               | Could not get balance for BG/Resource '%s' due to deadlock, the transcation will be canceled and retried.    | 18507
ERR_APPLYBAL_REALTIME               | Apply Balance plugin not required for Realtime mode.  | 18508
ERR_NO_SUBBALIMPACT                 | No sub-balance impact created for BG/Resource '%s', discount not granted for this EDR. Make sure the resource is valid and there is a check for available resource in the configuration. | 18509
ERR_APPLYBAL_NO_PREFIX              | No Prefix Specified For The Notification File Name | 18511
WRN_APPLYBAL_LOCKED                 | Could not update balance for BG/Resource '%s' due to balance group is locked. '%s'. | 18512
