ERR_ICPRODUCT_NETWORKMODEL_NOT_FOUND      | Network model '%s' not found.	| 18201
ERR_ICPRODUCT_NOT_FOUND         | IC_PRODUCT for GROUP/TR+DIR=%s, DATE=%s, SNW=%s, DNW=%s, A#=%s, B#=%s, C#=%s, RecT=%s, SCODE=%s, SCLASS=%s and UC=%s not found (Reason '%s').	| 18202
ERR_ICPRODUCT_INVALID           | No valid entry in IFW_ICPRODUCT_RATE found for NM=%s, NO=%s, ICPRODUCT=%s and Date=%s.	| 18203
ERR_INVALID_MODELTYPE           | %s	| 18204
ERR_TRUNK_NOT_FOUND             | No entry found for trunk under GSM extension | 18205
