#===============================================================================
# $Id: FCT_USC_Map_Error.msg,v 1.1 2001/09/18 12:31:44 dhatton Exp $
#
# $RCSfile: FCT_USC_Map_Error.msg,v $
# $Revision: 1.1 $
# $Author: dhatton $
# $Date: 2001/09/18 12:31:44 $
# $Locker:  $
#-------------------------------------------------------------------------------
# $Log: FCT_USC_Map_Error.msg,v $
# Revision 1.1  2001/09/18 12:31:44  dhatton
# Error messages!
#
#===============================================================================
#Errors
ERR_SETUP_USC_MAPTABLE                  | Failed to initialise the USC map table (%s).  | 17401
ERR_USC_GROUP_VALUE_NOT_FOUND           | No specified for USC group registry parameter.        | 17402

#Info.
INF_READING_USC                         | Reading USC map file (%s).                    | 17403
INF_USC_MAP_ENTRIES_LOADED              | %s USC mapping entries loaded.                | 17404
INF_NO_USC_MAPPING_ENTRY                | No USC Mapping Entry  (%s)                    | 17405
