#===============================================================================
# $Id: FCT_Splitting_Error.msg,v 1.1 2001/09/13 15:04:14 dhatton Exp $
#
# $RCSfile: FCT_Splitting_Error.msg,v $
# $Revision: 1.1 $
# $Author: dhatton $
# $Date: 2001/09/13 15:04:14 $
# $Locker:  $
#-------------------------------------------------------------------------------
# $Log: FCT_Splitting_Error.msg,v $
# Revision 1.1  2001/09/13 15:04:14  dhatton
# Initial checkin.
#
#===============================================================================

ERR_NO_OUTPUT_STREAM_SPECIFIED          | Registry error: no output stream name given for system brand %s .     | 17101
