#===============================================================================
# $Id: FCT_UoM_Map_Error.msg,v 1.1 2001/09/18 12:39:45 dhatton Exp $
#
# $RCSfile: FCT_UoM_Map_Error.msg,v $
# $Revision: 1.1 $
# $Author: dhatton $
# $Date: 2001/09/18 12:39:45 $
# $Locker:  $
#-------------------------------------------------------------------------------
# $Log: FCT_UoM_Map_Error.msg,v $
# Revision 1.1  2001/09/18 12:39:45  dhatton
# Error messages.
#
#===============================================================================
#Errors
ERR_INIT_UoM_MAPTABLE                   | Failed to intiialise the UoM map table (%s).  | 17201
ERR_INIT_PBC_SERVICE_MAP_TABLE          | Failed to init. service map table (%s).       | 17202
ERR_INIT_PBC_SERVICE_RGL_MAP_TABLE      | Failed to init. rgl map table (%s).           | 17203
ERR_NO_SERVICE_CODE_NAME_SUPPLIED       | No service code value was supplied for the mapping (%s).      | 17204

#Warnings
 
#Info.
