INF_DUPLICATE_COUNT     | '%s' Duplicate EDRs found.
INF_DUPLICATE_EDR       | EDR is a duplicate.
WRN_EMPTY_FIELD         | One key field is empty, field ignored.
WRN_DUP_RECORD          | Duplicate record found in the file
WRN_NO_ROOT_FIELD       | Defined field is not in the root block.
WRN_MAIN_FILE_NOT_FOUND | Main data file not found.
ERR_DUP_IND_FIELD_TYPE  | Wrong duplicate indicator field type (requires INTEGER).
ERR_FLUSH_TO_FILE       | Could not flush data to the file.
ERR_REMOVE_FILE         | Could not remove the File '%s'.
ERR_PROC_EXEC_FAILED    | Procedure: '%s' execute failed, '%s'.
ERR_PROC_MISSING        | Procedure: '%s' does not exist
ERR_INSERTION_FAILED    | Insertion in the table '%s' failed. Error: '%s'.
ERR_DELETION_FAILED     | Deletion in the table '%s' failed for the TransId: '%d'. Error: '%s'.
ERR_BULKINSERTION_FAILED | Bulk Insertion Failed in the table '%s' from the File '%s'. Error: '%s'.
ERR_INSERT_MAP_FAILED    | Insertion into the DuplicateCheck Map failed from the File: '%s'.
ERR_NO_TABLESPACE_CONF   | TableSpaceName entry is not specified in the FCT_DuplicateCheck module in the registry. It is mandatory if the Database mode is configured.
ERR_NO_INDEXSPACE_CONF   | IndexSpaceName entry is not specified in the FCT_DuplicateCheck module in the registry. It is mandatory if the Database mode is configured.
