#===============================================================================
# $Id: FCT_ServiceCodeMap_Error.msg,v 1.1 2001/09/18 12:17:48 dhatton Exp $
#
# $RCSfile: FCT_ServiceCodeMap_Error.msg,v $
# $Revision: 1.1 $
# $Author: dhatton $
# $Date: 2001/09/18 12:17:48 $
# $Locker:  $
#-------------------------------------------------------------------------------
# $Log: FCT_ServiceCodeMap_Error.msg,v $
# Revision 1.1  2001/09/18 12:17:48  dhatton
# Error message!
#
#===============================================================================

# edr errors

# info messages

# error messages
