#=================================================================
# Infranet Pipeline Server INP::GenericStream Messages
#
# Number Range: 10201-10300
#----------------------------------------------------------------
# Note: Add only numbers inside the allocated range.
#       Do not change existing numbers.
#=================================================================
# 07-Aug-2003: Introduction of error number ranges
#=================================================================

ERR_INP_GENERICSTREAM_PARSE_ERROR_STREAM | Parse error on input stream '%s': %s. | 10201
