ERR_SOCKET_BIND  | Socket bind error .     | 11001
ERR_CREATE_CONTEXT_FAILED  | PCM_CREATE_CONTEXT failed for socket '%s'. | 11002
ERR_OPEN_REALTIME_TRANSACTION  | Failed to open realtime transaction in pipeline '%s'. | 11003
ERR_CLOSE_REALTIME_TRANSACTION  | Failed to close realtime transaction in pipeline '%s'. | 11004
ERR_SOCK_BIND  | TCP/IP Socket bind error '%s', errno '%s'.     | 11005
INF_SOCK_BIND  | TCP/IP Socket bind done for TCP/IP port '%s'.     | 11006
ERR_LSOCK_BIND  | Unix Sock bind error for filename '%s'.     | 11007
INF_LSOCK_BIND  | Unix Sock bind done for filename '%s'.     | 11008
ERR_RTP_ARE_NOT_READY  | All Realtime Pipelines NOT ready.  | 11009
INF_RTP_ARE_READY  | All Realtime Pipelines ready.  | 11010
ERR_OPCODE_NOT_CONFIGURED  | Opcode '%s' is not configured.     | 11011
ERR_SOCK_LISTEN  | Listen failed for socket '%s', errno '%s'.| 11012
INF_SOCK_LISTEN  | Listen done for socket '%s' . | 11013
ERR_SOCK_ACCEPT  | Accept failed for socket '%s', errno '%s'. | 11014
INF_SOCK_ACCEPT  | Accept done for socket '%s', return sock id is '%s' .     | 11015
