#=================================================================
# Operation Management Framework (OMF)
#
# Number Range: 11301-11400
#----------------------------------------------------------------
# Note: Add only numbers inside the allocated range.
#       Do not change existing numbers.
#=================================================================

ERR_SNMP_SUBAGENT_MIB_INIT              | Failed to initialize SNMP subagent mib.  Registration will be re-attempted periodically. | 11301
ERR_SNMP_NOT_REGISTERED	                | Failed to register the mib table OID %s for probe %s at master SNMP agent. | 11302
ERR_SNMP_LOST_CONNECTION                | Lost connection to master SNMP agent. | 11303
INF_SNMP_RECONNECT                      | Successfully reconnected to master SNMP agent.  Mib tables re-initialized. | 11304
ERR_SNMP_NOT_UNREGISTERED               | Failed to un-register the mib table OID %s for probe %s at master SNMP agent. | 11305
INF_SNMP_INIT_REGISTRATION_SUCCESS      | Initial mib tables registration completed successfully. | 11306
