##################################################################
# $Id: OUT_GenericStream_Error.msg,v 1.2 2001/09/26 06:59:29 sd Exp $
#
# INP_GenericStream error messages
##################################################################

ERR_OUTPUT_PARSE_ERROR             | Parse error on output file '%s': %s.
ERR_STREAM_IS_EMPTY_RETURN         | Function streamIsEmpty() needs boolean return type.
