#=================================================================
# Portal Pipeline Server INP::Realtime Messages
#
# Number Range: 10901-11000
#----------------------------------------------------------------
# Note: Add only numbers inside the allocated range.
#       Do not change existing numbers.
#=================================================================
# 07-Feb-2005: Initial version
#=================================================================

WRN_OUT_REALTIME_REVERSE_RATING_APPLIED    | RealtimePipeline: Reverse Rating Applied.   | 10901
