INF_DELETE_WITHOUT_DETAILS  | Registry-Parameter DeleteWithoutDetail is set to '%s'.
INF_WRITE_DEFAULT_EDR       | Registry-Parameter WriteDefaultEdr is set to '%s'.
ERR_INDEXLIST_NOT_CREATED   | Couldn't create index table for edr-container fields.
INF_DB_STREAM_OPENED        | Database opened for stream '%s'.
ERR_DB_STREAM_OPEN          | Database open failed for stream '%s'.
INF_DB_STREAM_CLOSED        | Database closed for stream '%s'.
ERR_DB_STREAM_CLOSE         | Database could not closed for stream '%s'.
INF_DB_OUTPUT_STR_STATEMENT | SQL-Statment for '%s': '%s'.
INF_DB_STREAM_COMMITED      | Database transaction commited for stream '%s'.
INF_DB_STREAM_ROLLEDBACK    | Database transaction rollbacked for stream '%s'.
ERR_DB_ROLLBACK_TRANSACTION | Database transaction collback failed for stream '%s'.
ERR_FILE_NOT_CONSISTENT     | Parameter '%s' file not consistent.
