#=================================================================
# Infranet Pipeline Server Framework Messages
#
# Number Range: 10001-10100
#----------------------------------------------------------------
# Note: Add only numbers inside the allocated range.
#       Do not change existing numbers.
#=================================================================
# 05-Aug-2003: Introduction of error number ranges
#=================================================================

ERR_WRONG_INFILEMGR    | Input file manager '%s' is not of type EXT_InFileManager | 10001
ERR_RENAME_FILE_FAILED | Failed to rename file '%s'                               | 10002
