INSERT INTO IFW_NETWORKOPER ( NO, CODE, NAME, NOTYPE, CAC, CIC, PLMN_ID, TADIG, CURRENCY, TAXGROUP,TAXFLAG,DECIMAL_PLACES,CAMELFLAG,NRTRDEFLAG,COUNTRYCODE ) VALUES ( 
1, 'EUR01', 'EUR01', 'O', NULL, NULL, 'EUR01', NULL, 'DEM', 'NORM', 'Y', 5, 'N', 'N', 42 ); 
INSERT INTO IFW_NETWORKOPER ( NO, CODE, NAME, NOTYPE, CAC, CIC, PLMN_ID, TADIG, CURRENCY, TAXGROUP,TAXFLAG,DECIMAL_PLACES,CAMELFLAG,NRTRDEFLAG,COUNTRYCODE ) VALUES ( 
2, 'OPRT1', 'OPRT1', 'O', NULL, NULL, 'OPRT1', NULL, 'USD', 'NORM', 'N',5, 'N', 'N', 42 ); 
INSERT INTO IFW_NETWORKOPER ( NO, CODE, NAME, NOTYPE, CAC, CIC, PLMN_ID, TADIG, CURRENCY, TAXGROUP,TAXFLAG,DECIMAL_PLACES,CAMELFLAG,NRTRDEFLAG,COUNTRYCODE ) VALUES ( 
3, 'OPRT2', 'OPRT2', 'O', NULL, NULL, 'OPRT2', NULL, 'USD', 'NORM', 'N',5, 'N', 'N', 42 ); 
COMMIT;
