INSERT INTO IFW_DSCCONDITION ( DISCOUNTCONDITION, DISCOUNTTRIGGER, COND_EXPRESSION, 
COND_OPERATOR, CONDITION_VALUE ) VALUES ( 
IFW_SEQ_DISCOUNTCONDITION.NEXTVAL,(SELECT DISCOUNTTRIGGER FROM IFW_DSCTRIGGER WHERE CODE='DT10%OFF'), 'TotalC', 'GE', 0); 
INSERT INTO IFW_DSCCONDITION ( DISCOUNTCONDITION, DISCOUNTTRIGGER, COND_EXPRESSION, 
COND_OPERATOR, CONDITION_VALUE ) VALUES ( 
IFW_SEQ_DISCOUNTCONDITION.NEXTVAL,(SELECT DISCOUNTTRIGGER FROM IFW_DSCTRIGGER WHERE CODE='DTFMALL'), 'BAL(1000095)', 'LT', 0); 
INSERT INTO IFW_DSCCONDITION ( DISCOUNTCONDITION, DISCOUNTTRIGGER, COND_EXPRESSION, 
COND_OPERATOR, CONDITION_VALUE ) VALUES ( 
IFW_SEQ_DISCOUNTCONDITION.NEXTVAL,(SELECT DISCOUNTTRIGGER FROM IFW_DSCTRIGGER WHERE CODE='CT10%OFF'), 'TotalC', 'GT', 0); 
commit;
 
