INSERT INTO IFW_DISCOUNTMODEL ( DISCOUNTMODEL, CODE, NAME, CHARGESHARE_FLAG ) VALUES ( 
IFW_SEQ_DISCOUNTMODEL.NEXTVAL, 'DM10%OFF', 'Discount Model for Taking 10% Discount', 0); 
INSERT INTO IFW_DISCOUNTMODEL ( DISCOUNTMODEL, CODE, NAME, CHARGESHARE_FLAG ) VALUES ( 
IFW_SEQ_DISCOUNTMODEL.NEXTVAL, 'DMFMALL', 'Discount Model for Consuming Free Minutes (Using ResourceId 1000095)', 0); 
INSERT INTO IFW_DISCOUNTMODEL ( DISCOUNTMODEL, CODE, NAME, CHARGESHARE_FLAG ) VALUES ( 
IFW_SEQ_DISCOUNTMODEL.NEXTVAL, 'CS10%OFF', 'Charge Share 10% OFF', 1); 
commit;
 
