INSERT INTO IFW_RATEPLAN ( RATEPLAN, CODE, NAME, STATUS, SYSTEM_BRAND, MODELTYPE, SPLITTING,
CALENDAR, UTC_TIME_OFFSET, CURRENCY, TAXTREATMENT ) VALUES ( 
20001, 'Standard', 'Standard', 'A', NULL, 'R', 1, 20000, '+0100', 'EUR', 0); 
INSERT INTO IFW_RATEPLAN ( RATEPLAN, CODE, NAME, STATUS, SYSTEM_BRAND, MODELTYPE, SPLITTING,
CALENDAR, UTC_TIME_OFFSET, CURRENCY, TAXTREATMENT ) VALUES ( 
20002, 'CorpPlus', 'Corporate Plus', 'A', NULL, 'R', 1, 20000, '+0100', 'EUR', 0); 
INSERT INTO IFW_RATEPLAN ( RATEPLAN, CODE, NAME, STATUS, SYSTEM_BRAND, MODELTYPE, SPLITTING,
CALENDAR, UTC_TIME_OFFSET, CURRENCY, TAXTREATMENT ) VALUES ( 
20003, 'gprs', 'GPRS Sample Rateplan', 'A', NULL, 'R', 1, 20000, '+0100', 'EUR', 0); 
INSERT INTO IFW_RATEPLAN ( RATEPLAN, CODE, NAME, STATUS, SYSTEM_BRAND, MODELTYPE, SPLITTING,
CALENDAR, UTC_TIME_OFFSET, CURRENCY, TAXTREATMENT ) VALUES ( 
20004, 'Teen', 'Teen', 'A', NULL, 'R', 1, 20000, '+0100', 'EUR', 0); 
INSERT INTO IFW_RATEPLAN ( RATEPLAN, CODE, NAME, STATUS, SYSTEM_BRAND, MODELTYPE, SPLITTING,
CALENDAR, UTC_TIME_OFFSET, CURRENCY, TAXTREATMENT ) VALUES ( 
20005, 'gsm', 'GSM Sample Rateplan', 'A', NULL, 'R', 1, 20000, '+0100', 'EUR', 0); 
commit;
 
