INSERT INTO IFW_NETWORKMODEL ( NETWORKMODEL, CODE, NAME, CALCMODE, MODELTYPE, USE_SWITCH,USE_FIXCOST, SYSTEM_BRAND, 
RATEPLAN, NO, CURRENCY) VALUES ( 
1, 'Standard', 'Own', '3', 'O', 0, 0, NULL, NULL, 1, 'DEM'); 
COMMIT;
