INSERT INTO IFW_TAXCODE ( TAXCODE, NAME ) VALUES ( 
'NORM', 'Normal Tax'); 
INSERT INTO IFW_TAXCODE ( TAXCODE, NAME ) VALUES ( 
'REDUC', 'Reduced Tax'); 
INSERT INTO IFW_TAXCODE ( TAXCODE, NAME ) VALUES ( 
'ZERO', 'No Tax'); 
commit;
 
