INSERT INTO IFW_RESOURCE ( RESOURCE_NAME, SYMBOL, TYPE, CURRENCY ) VALUES ( 
'DOLLAR', '$', 'M', 'USD'); 
INSERT INTO IFW_RESOURCE ( RESOURCE_NAME, SYMBOL, TYPE, CURRENCY ) VALUES ( 
'EURO', 'EUR', 'M', 'EUR'); 
INSERT INTO IFW_RESOURCE ( RESOURCE_NAME, SYMBOL, TYPE, CURRENCY ) VALUES ( 
'LOYALTY', 'LOY', 'O', NULL); 
INSERT INTO IFW_RESOURCE ( RESOURCE_NAME, SYMBOL, TYPE, CURRENCY ) VALUES ( 
'SUM_DUR', 'DUR', 'O', NULL); 
INSERT INTO IFW_RESOURCE ( RESOURCE_NAME, SYMBOL, TYPE, CURRENCY ) VALUES (
'SDR', 'SDR', 'M', 'SDR');
commit;
 
