INSERT INTO IFW_EXCHANGE_RATE ( FROM_CURRENCY, VALID_FROM, TO_CURRENCY, EXCHANGE_RATE) VALUES ( 
'EUR',  TO_Date( '01/01/1999 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'SDR', 0.83);
INSERT INTO IFW_EXCHANGE_RATE ( FROM_CURRENCY, VALID_FROM, TO_CURRENCY, EXCHANGE_RATE) VALUES ( 
'SDR',  TO_Date( '01/01/1999 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'EUR', 1.2);
COMMIT;
