INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20381, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_IMSI', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20382, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_IMSI', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20383, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_STATUS', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20384, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_STATUS', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20385, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_ITEM_POID', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20386, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_ITEM_POID', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20387, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_NEXT_ITEM_POID', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20388, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_NEXT_ITEM_POID', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20389, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_USED_ITEM_POID', 'String', 'mandatory  '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20390, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_USED_ITEM_POID', 'String', 'mandatory  '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20391, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.NETWORK_IDENT', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20392, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.NETWORK_IDENT', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20393, 'ALL_RATE', 'DETAIL.CUST_A.ERA.PROFILE', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20394, 'ALL_RATE', 'DETAIL.CUST_B.ERA.PROFILE', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20395, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.ERA.PROFILE', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20396, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.ERA.PROFILE', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20397, 'ALL_RATE', 'DETAIL.CUST_A.ERA.PA.KEY', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20398, 'ALL_RATE', 'DETAIL.CUST_B.ERA.PA.KEY', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20399, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.ERA.PA.KEY', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20400, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.ERA.PA.KEY', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20401, 'ALL_RATE', 'DETAIL.CUST_A.ERA.PA.VALUE', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20402, 'ALL_RATE', 'DETAIL.CUST_B.ERA.PA.VALUE', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20403, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.ERA.PA.VALUE', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20404, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.ERA.PA.VALUE', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20405, 'ALL_RATE', 'DETAIL.CUST_A.ERA.PA.VALID_FROM', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20406, 'ALL_RATE', 'DETAIL.CUST_B.ERA.PA.VALID_FROM', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20407, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.ERA.PA.VALID_FROM', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20408, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.ERA.PA.VALID_FROM', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20409, 'ALL_RATE', 'DETAIL.CUST_A.ERA.PA.VALID_TO', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20410, 'ALL_RATE', 'DETAIL.CUST_B.ERA.PA.VALID_TO', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20411, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.ERA.PA.VALID_TO', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20412, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.ERA.PA.VALID_TO', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20413, 'ALL_RATE', 'DETAIL.CUST_A', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20414, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.SS_PACKET', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20415, 'ALL_RATE', 'DETAIL.CUST_B', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20416, 'ALL_RATE', 'DETAIL.CUST_A.ERA.PA', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20417, 'ALL_RATE', 'DETAIL.CUST_B.ERA.PA', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20418, 'ALL_RATE', 'DETAIL.CUST_A.ERA', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20419, 'ALL_RATE', 'DETAIL.CUST_B.ERA', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20420, 'ALL_RATE', 'DETAIL.ASS_ZBD', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20421, 'ALL_RATE', 'HEADER', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20422, 'ALL_RATE', 'DETAIL.ASS_PIN.BP', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20423, 'ALL_RATE', 'DETAIL.ASS_PIN', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20424, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20425, 'ALL_RATE', 'DETAIL.ASS_CBD', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20426, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20427, 'ALL_RATE', 'DETAIL.ASS_CBD.CP', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20428, 'ALL_RATE', 'DETAIL', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20429, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20430, 'ALL_RATE', 'TRAILER', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20431, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.ERA.PA', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20432, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.ERA.PA', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20433, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.ERA', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20434, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20435, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.ERA', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20436, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20437, 'ALL_RATE', 'INTERNAL', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20438, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20439, 'ALL_RATE', 'DETAIL.ASS_ZBD.ZP', 'Block', NULL); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20309, 'ALL_RATE', 'TRAILER.ORIGIN_SEQUENCE_NUMBER', 'Integer', 'calculated, same as above, if present it must held the '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20310, 'ALL_RATE', 'TRAILER.TOTAL_NUMBER_OF_RECORDS', 'Integer', 'calculated, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20311, 'ALL_RATE', 'TRAILER.FIRST_START_TIMESTAMP', 'Date', 'calculated, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20312, 'ALL_RATE', 'TRAILER.FIRST_CHARGING_UTC_TIME_OFFSET', 'String', 'calculated, auto-generated, default=HEADER.UTC_TIME_OFFSET'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20313, 'ALL_RATE', 'TRAILER.LAST_START_TIMESTAMP', 'Date', 'calculated, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20314, 'ALL_RATE', 'TRAILER.LAST_CHARGING_UTC_TIME_OFFSET', 'String', 'calculated, auto-generated, default=HEADER.UTC_TIME_OFFSET'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20315, 'ALL_RATE', 'TRAILER.TOTAL_RETAIL_CHARGED_VALUE', 'Decimal', 'calculated, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20316, 'ALL_RATE', 'TRAILER.TOTAL_WHOLESALE_CHARGED_VALUE', 'Decimal', 'calculated, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20317, 'ALL_RATE', 'INTERNAL.STREAM_NAME', 'String', 'calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20318, 'ALL_RATE', 'INTERNAL.OFFSET_GENERATION', 'Integer', 'calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20319, 'ALL_RATE', 'INTERNAL.SEQ_CHECK', 'Integer', 'calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20320, 'ALL_RATE', 'INTERNAL.SEQ_GENERATION', 'Integer', 'calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20321, 'ALL_RATE', 'INTERNAL.TRANSACTION_ID', 'Decimal', 'calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20322, 'ALL_RATE', 'INTERNAL.PROCESS_STATUS', 'Integer', 'mandatory-calculated, default=0 - possible values are 0=normal, '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20323, 'ALL_RATE', 'DETAIL.CUST_A.ACCOUNT_ID', 'String', 'mandatory, <db#>_<id0> (e.g. "1_4711")'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20324, 'ALL_RATE', 'DETAIL.CUST_B.ACCOUNT_ID', 'String', 'mandatory, <db#>_<id0> (e.g. "1_4711")'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20325, 'ALL_RATE', 'DETAIL.CUST_A.ACCOUNT_PARENT_ID', 'String', 'optional, <db#>_<id0> (e.g. "1_4711")'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20326, 'ALL_RATE', 'DETAIL.CUST_B.ACCOUNT_PARENT_ID', 'String', 'optional, <db#>_<id0> (e.g. "1_4711")'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20327, 'ALL_RATE', 'DETAIL.CUST_A.ACCOUNT_NO', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20328, 'ALL_RATE', 'DETAIL.CUST_B.ACCOUNT_NO', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20329, 'ALL_RATE', 'DETAIL.CUST_A.CREATION_DATE', 'Date', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20330, 'ALL_RATE', 'DETAIL.CUST_B.CREATION_DATE', 'Date', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20331, 'ALL_RATE', 'DETAIL.CUST_A.CURRENCY', 'String', 'mandatory, e.g. "USD", "EUR", "DEM", ...'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20332, 'ALL_RATE', 'DETAIL.CUST_B.CURRENCY', 'String', 'mandatory, e.g. "USD", "EUR", "DEM", ...'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20333, 'ALL_RATE', 'DETAIL.CUST_A.RESIDENCE_TYPE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20334, 'ALL_RATE', 'DETAIL.CUST_B.RESIDENCE_TYPE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20335, 'ALL_RATE', 'DETAIL.CUST_A.SYSTEM_BRAND', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20336, 'ALL_RATE', 'DETAIL.CUST_B.SYSTEM_BRAND', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20337, 'ALL_RATE', 'DETAIL.CUST_A.BILL_CYCLE', 'String', 'mandatory, 00-28'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20338, 'ALL_RATE', 'DETAIL.CUST_B.BILL_CYCLE', 'String', 'mandatory, 00-28'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20339, 'ALL_RATE', 'DETAIL.CUST_A.BILL_FREQUENCY', 'Integer', 'mandatory, 1-12'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20340, 'ALL_RATE', 'DETAIL.CUST_B.BILL_FREQUENCY', 'Integer', 'mandatory, 1-12'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20341, 'ALL_RATE', 'DETAIL.CUST_A.PAYMENT_TYPE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20342, 'ALL_RATE', 'DETAIL.CUST_B.PAYMENT_TYPE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20343, 'ALL_RATE', 'DETAIL.CUST_A.ACTG_LAST_DATE', 'Date', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20344, 'ALL_RATE', 'DETAIL.CUST_B.ACTG_LAST_DATE', 'Date', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20345, 'ALL_RATE', 'DETAIL.CUST_A.ACTG_NEXT_DATE', 'Date', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20346, 'ALL_RATE', 'DETAIL.CUST_B.ACTG_NEXT_DATE', 'Date', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20347, 'ALL_RATE', 'DETAIL.CUST_A.ACTG_USED_DATE', 'Date', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20348, 'ALL_RATE', 'DETAIL.CUST_B.ACTG_USED_DATE', 'Date', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20349, 'ALL_RATE', 'DETAIL.CUST_A.INTERN_FOUND_PP_INDEX', 'Integer', 'mandatory - represents the purchased '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20350, 'ALL_RATE', 'DETAIL.CUST_B.INTERN_FOUND_PP_INDEX', 'Integer', 'mandatory - represents the purchased '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20351, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.PRODUCT_NAME', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20352, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.PRODUCT_NAME', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20353, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.USAGE_START', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20354, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.USAGE_START', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20355, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.USAGE_END', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20356, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.USAGE_END', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20357, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.QUANTITY', 'Decimal', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20358, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.QUANTITY', 'Decimal', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20359, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.DEAL_NAME', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20360, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.DEAL_NAME', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20361, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.PLAN_NAME', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20362, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.PLAN_NAME', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20363, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.RATEPLAN_NAME', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20364, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.RATEPLAN_NAME', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20365, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.PRODUCT_ID', 'String', 'optional, <db#>_<id0> (e.g. "1_6789")'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20366, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.PRODUCT_ID', 'String', 'optional, <db#>_<id0> (e.g. "1_6789")'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20367, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_TYPE', 'String', 'mandatory, e.g. " service gsm sms"'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20368, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_TYPE', 'String', 'mandatory, e.g. " service gsm sms"'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20369, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_ID', 'String', 'optional, <db#>_<id0> (e.g. "1_12345")'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20370, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_ID', 'String', 'optional, <db#>_<id0> (e.g. "1_12345")'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20371, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_PROMO_CODE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20372, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_PROMO_CODE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20373, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_VENDOR', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20374, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_VENDOR', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20375, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_SOURCE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20376, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_SOURCE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20377, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_LOGIN', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20378, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_LOGIN', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20379, 'ALL_RATE', 'DETAIL.CUST_A.PRODUCT.SERVICE_MSISDN', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20380, 'ALL_RATE', 'DETAIL.CUST_B.PRODUCT.SERVICE_MSISDN', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20025, 'ALL_RATE', 'DETAIL.SOURCE_NETWORK', 'String', 'optional (but might be mandatory in order to recognize specific '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20026, 'ALL_RATE', 'DETAIL.DESTINATION_NETWORK_TYPE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20027, 'ALL_RATE', 'DETAIL.DESTINATION_NETWORK', 'String', 'optional (but might be mandatory in order to recognize specific '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20028, 'ALL_RATE', 'DETAIL.TYPE_OF_A_IDENTIFICATION', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20029, 'ALL_RATE', 'DETAIL.A_MODIFICATION_INDICATOR', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20030, 'ALL_RATE', 'DETAIL.A_TYPE_OF_NUMBER', 'Integer', 'optional, but should be defaulted to ''0''. Could be used by some '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20031, 'ALL_RATE', 'DETAIL.A_NUMBERING_PLAN', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20032, 'ALL_RATE', 'DETAIL.A_NUMBER', 'String', 'mandatory!, will be used to identify the billable party (could '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20033, 'ALL_RATE', 'DETAIL.B_MODIFICATION_INDICATOR', 'String', 'optional-calculated, might be used to identify Social-Numbers'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20034, 'ALL_RATE', 'DETAIL.B_TYPE_OF_NUMBER', 'Integer', 'optional, but should be defaulted to ''0''. Could be used by some '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20035, 'ALL_RATE', 'DETAIL.B_NUMBERING_PLAN', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20036, 'ALL_RATE', 'DETAIL.B_NUMBER', 'String', 'mandatory!, will be used to identify the other party (could '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20037, 'ALL_RATE', 'DETAIL.DESCRIPTION', 'String', 'calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20038, 'ALL_RATE', 'DETAIL.C_MODIFICATION_INDICATOR', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20039, 'ALL_RATE', 'DETAIL.C_TYPE_OF_NUMBER', 'Integer', 'optional, but should be defaulted to ''0''. Could be used by some '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20040, 'ALL_RATE', 'DETAIL.C_NUMBERING_PLAN', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20041, 'ALL_RATE', 'DETAIL.C_NUMBER', 'String', 'optional, but might be used in order to be able to detect '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20042, 'ALL_RATE', 'DETAIL.USAGE_DIRECTION', 'String', 'mandatory, default=0'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20043, 'ALL_RATE', 'DETAIL.CONNECT_TYPE', 'String', 'optional, but might be used in order to be able to detect '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20044, 'ALL_RATE', 'DETAIL.CONNECT_SUB_TYPE', 'String', 'optional, but might be used in order to be able to detect '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20045, 'ALL_RATE', 'DETAIL.BASIC_SERVICE', 'String', 'mandatory!, default=''011'', will be used to identify which '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20046, 'ALL_RATE', 'DETAIL.QOS_REQUESTED', 'String', 'calculated, but might be used in order to be able to detect '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20047, 'ALL_RATE', 'DETAIL.QOS_USED', 'String', 'calculated, but might be used in order to be able to detect '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20048, 'ALL_RATE', 'DETAIL.CALL_COMPLETION_INDICATOR', 'String', 'default, but should be defaulted with ''C'' or ''00'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20049, 'ALL_RATE', 'DETAIL.LONG_DURATION_INDICATOR', 'String', 'mandatory, default=''S'' (might be used for assembling events '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20050, 'ALL_RATE', 'DETAIL.CHARGING_START_TIMESTAMP', 'Date', 'mandatory!'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20051, 'ALL_RATE', 'DETAIL.CHARGING_END_TIMESTAMP', 'Date', 'optional, might be used to calculate the DURATION'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20052, 'ALL_RATE', 'DETAIL.UTC_TIME_OFFSET', 'String', 'default, default=<local_time_zone>, e.g. ''+0100'' for europe'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20053, 'ALL_RATE', 'DETAIL.DURATION', 'Decimal', 'mandatory!, default=0 - should be set for all time-based '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20054, 'ALL_RATE', 'DETAIL.DURATION_UOM', 'String', 'mandatory, default=''SEC'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20055, 'ALL_RATE', 'DETAIL.VOLUME_SENT', 'Decimal', 'mandatory!, default=0 - should be set for all volume-based '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20056, 'ALL_RATE', 'DETAIL.VOLUME_SENT_UOM', 'String', 'mandatory, default=''BYT'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20057, 'ALL_RATE', 'DETAIL.VOLUME_RECEIVED', 'Decimal', 'mandatory!, dafault=0 - should be set for all volume-based '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20058, 'ALL_RATE', 'DETAIL.VOLUME_RECEIVED_UOM', 'String', 'mandatory, default=''BYT'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20059, 'ALL_RATE', 'DETAIL.NUMBER_OF_UNITS', 'Decimal', 'mandatory!, dafault=0 - should be set for all event-based '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20060, 'ALL_RATE', 'DETAIL.NUMBER_OF_UNITS_UOM', 'String', 'mandatory, default=''CLK'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20061, 'ALL_RATE', 'DETAIL.RETAIL_IMPACT_CATEGORY', 'String', 'calculated, will be used by zoning and rating plugins'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20001, 'ALL_RATE', 'HEADER.RECORD_LENGTH', 'Integer', 'optional for backward compatibility'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20002, 'ALL_RATE', 'HEADER.RECORD_TYPE', 'String', 'mandatory, must be set to ''010'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20003, 'ALL_RATE', 'HEADER.RECORD_NUMBER', 'Integer', 'mandatory, should be set to ''1'', auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20004, 'ALL_RATE', 'HEADER.SENDER', 'String', 'optional, but should be defaulted if not present on the input '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20005, 'ALL_RATE', 'HEADER.RECIPIENT', 'String', 'optional, but should be defaulted if not present on the '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20006, 'ALL_RATE', 'HEADER.SEQUENCE_NUMBER', 'Integer', 'optional, if no sequence-check is performed. mandatory, if a '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20007, 'ALL_RATE', 'HEADER.ORIGIN_SEQUENCE_NUMBER', 'Integer', 'optional, will by set with the SEQUENCE_NUMBER by the sequence in'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20008, 'ALL_RATE', 'HEADER.CREATION_TIMESTAMP', 'Date', 'default, default=filesystem-date'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20009, 'ALL_RATE', 'HEADER.TRANSMISSION_DATE', 'Date', 'default, default=sysdate - as the input delivers no time-part '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20010, 'ALL_RATE', 'HEADER.TRANSFER_CUTOFF_TIMESTAMP', 'Date', 'default, default=TRANSMISSION_DATE'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20011, 'ALL_RATE', 'HEADER.UTC_TIME_OFFSET', 'String', 'default, default=<local_time_zone>, e.g. ''+0100'' for europe'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20012, 'ALL_RATE', 'HEADER.SPECIFICATION_VERSION_NUMBER', 'Integer', 'default, default=''04'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20013, 'ALL_RATE', 'HEADER.RELEASE_VERSION', 'Integer', 'default, default=''03'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20014, 'ALL_RATE', 'HEADER.ORIGIN_COUNTRY_CODE', 'String', 'optional, should be default=<iac><cc> of country where the '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20015, 'ALL_RATE', 'HEADER.SENDER_COUNTRY_CODE', 'String', 'optional, should be default=<iac><cc> of country where the '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20016, 'ALL_RATE', 'HEADER.DATA_TYPE_INDICATOR', 'String', 'mandatory, default=<space> for chargable data'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20017, 'ALL_RATE', 'HEADER.IAC_LIST', 'String', 'Comma separated list of possible IACs.'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20018, 'ALL_RATE', 'HEADER.CC_LIST', 'String', 'Comma separated list of possible CCs.'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20019, 'ALL_RATE', 'DETAIL.RECORD_LENGTH', 'Integer', 'optional for backward compatibility'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20020, 'ALL_RATE', 'DETAIL.RECORD_TYPE', 'String', 'mandatory, must be within the defined range (020-089, 100-299)'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20021, 'ALL_RATE', 'DETAIL.RECORD_NUMBER', 'Integer', 'mandatory, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20022, 'ALL_RATE', 'DETAIL.DISCARDING', 'Integer', 'mandatory, default=0'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20023, 'ALL_RATE', 'DETAIL.CHAIN_REFERENCE', 'String', 'optional (but mandatory, if an assembling plugin should '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20024, 'ALL_RATE', 'DETAIL.SOURCE_NETWORK_TYPE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20062, 'ALL_RATE', 'DETAIL.RETAIL_CHARGED_AMOUNT_VALUE', 'Decimal', 'calculated, will be used by rating plugins'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20063, 'ALL_RATE', 'DETAIL.RETAIL_CHARGED_AMOUNT_CURRENCY', 'String', 'calculated, will be used by rating plugins (could be either a '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20064, 'ALL_RATE', 'DETAIL.RETAIL_CHARGED_TAX_TREATMENT', 'String', 'calculated, default=''N'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20065, 'ALL_RATE', 'DETAIL.RETAIL_CHARGED_TAX_RATE', 'Integer', 'calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20066, 'ALL_RATE', 'DETAIL.WHOLESALE_IMPACT_CATEGORY', 'String', 'calculated, will be used by zoning and rating plugins'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20067, 'ALL_RATE', 'DETAIL.WHOLESALE_CHARGED_AMOUNT_VALUE', 'Decimal', 'calculated, will be used by rating plugins'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20068, 'ALL_RATE', 'DETAIL.WHOLESALE_CHARGED_AMOUNT_CURRENCY', 'String', 'calculated, will be used by rating plugins (could be either a '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20069, 'ALL_RATE', 'DETAIL.WHOLESALE_CHARGED_TAX_TREATMENT', 'String', 'calculated, default=''N'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20070, 'ALL_RATE', 'DETAIL.WHOLESALE_CHARGED_TAX_RATE', 'Integer', 'calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20071, 'ALL_RATE', 'DETAIL.TARIFF_CLASS', 'String', 'optional, but might be used in order to be able to detect '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20072, 'ALL_RATE', 'DETAIL.TARIFF_SUB_CLASS', 'String', 'optional, but might be used in order to be able to detect '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20073, 'ALL_RATE', 'DETAIL.USAGE_CLASS', 'String', 'calculated - used to hold a network-related usage scenario '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20074, 'ALL_RATE', 'DETAIL.USAGE_TYPE', 'String', 'calculated - used to hold a customer-related usage '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20075, 'ALL_RATE', 'DETAIL.BILLCYCLE_PERIOD', 'String', 'calculated - format=YYYYMMBC'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20076, 'ALL_RATE', 'DETAIL.PREPAID_INDICATOR', 'Integer', 'mandatory - indicates whether this event is a prepaid event'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20077, 'ALL_RATE', 'DETAIL.NUMBER_ASSOCIATED_RECORDS', 'Integer', 'calculated (but mandatory on the input side)'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20078, 'ALL_RATE', 'DETAIL.INTERN_A_NUMBER_ZONE', 'String', 'mandatory-calculated (equal to DETAIL.A_NUMBER), must be set '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20079, 'ALL_RATE', 'DETAIL.INTERN_B_NUMBER_ZONE', 'String', 'mandatory-calculated (equal to DETAIL.B_NUMBER), must be set '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20080, 'ALL_RATE', 'DETAIL.INTERN_C_NUMBER_ZONE', 'String', 'optional-calculated (equal to DETAIL.C_NUMBER), must be set by '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20081, 'ALL_RATE', 'DETAIL.INTERN_SERVICE_CODE', 'String', 'mandatory-calculated (equal to DETAIL.BASIC_SERVICE) - will be '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20082, 'ALL_RATE', 'DETAIL.INTERN_SERVICE_CLASS', 'String', 'optional-calculated (has to be defaulted with ''*'') - will be '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20083, 'ALL_RATE', 'DETAIL.INTERN_USAGE_CLASS', 'String', 'mandatory-calculated (equal to DETAIL.USAGE_CLASS), - will be '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20084, 'ALL_RATE', 'DETAIL.INTERN_ZONE_MODEL', 'Integer', 'mandatory-calculated - keeps the internal zonemodel-d to be used'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20085, 'ALL_RATE', 'DETAIL.INTERN_APN_GROUP', 'String', 'mandatory-calculated - keeps the internal apn_group-code to be '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20086, 'ALL_RATE', 'DETAIL.INTERN_BILLING_CURRENCY', 'String', 'mandatory-calculated - keeps the internal billing-currency to be '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20087, 'ALL_RATE', 'DETAIL.INTERN_HOME_CURRENCY', 'String', 'mandatory-calculated - keeps the internal home-currency to be '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20088, 'ALL_RATE', 'DETAIL.INTERN_SLA_USC_GROUP', 'String', 'mandatory-calculated - keeps the internal customer-related '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20089, 'ALL_RATE', 'DETAIL.INTERN_SLA_RSC_GROUP', 'String', 'mandatory-calculated - keeps the internal customer-related '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20090, 'ALL_RATE', 'DETAIL.INTERN_SLA_IRULE_SET', 'String', 'mandatory-calculated - keeps the internal customer-related '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20091, 'ALL_RATE', 'DETAIL.INTERN_PROCESS_STATUS', 'Integer', 'mandatory-calculated, default=0 - possible values are 0=normal, '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20092, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.RECORD_TYPE', 'String', 'mandatory, default=520'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20093, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.RECORD_NUMBER', 'Integer', 'mandatory, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20094, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.PORT_NUMBER', 'String', 'optional, (but might be mandatory for specific services in '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20095, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.DEVICE_NUMBER', 'String', 'optional, (e.g. IMEI)'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20096, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.A_NUMBER_USER', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20097, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.DIALED_DIGITS', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20098, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.BASIC_DUAL_SERVICE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20099, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.VAS_PRODUCT_CODE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20100, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.ORIGINATING_SWITCH_IDENTIFICATION', 'String'
, 'optional, (but might be mandatory for interconnection and to '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20101, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.TERMINATING_SWITCH_IDENTIFICATION', 'String'
, 'optional, (but might be mandatory for interconnection and to '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20102, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.TRUNK_INPUT', 'String', 'optional, (but might be mandatory for wireline services in order '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20103, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.TRUNK_OUTPUT', 'String', 'optional, (but might be mandatory for wireline services in order '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20104, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.LOCATION_AREA_INDICATOR', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20105, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.CELL_ID', 'String', 'optional, (but might be mandatory for specific rating scenarios, '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20106, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.MS_CLASS_MARK', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20107, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.TIME_BEFORE_ANSWER', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20108, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.BASIC_AOC_AMOUNT_VALUE', 'Decimal', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20109, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.BASIC_AOC_AMOUNT_CURRENCY', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20110, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.ROAMER_AOC_AMOUNT_VALUE', 'Decimal', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20111, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.ROAMER_AOC_AMOUNT_CURRENCY', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20112, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.NUMBER_OF_SS_PACKETS', 'Integer', 'mandatory, default=0'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20113, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.SS_PACKET.ACTION_CODE', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20114, 'ALL_RATE', 'DETAIL.ASS_GSMW_EXT.SS_PACKET.SS_EVENT', 'String', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20115, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.RECORD_TYPE', 'String', 'mandatory, default=540'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20116, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.RECORD_NUMBER', 'Integer', 'mandatory, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20117, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.PORT_NUMBER', 'String', 'optional, (but might be mandatory for specific services in order '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20118, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.DEVICE_NUMBER', 'String', 'optional, (e.g. IMEI)'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20119, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.A_NUMBER_USER', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20120, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.DIALED_DIGITS', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20121, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.VAS_PRODUCT_CODE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20122, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.ORIGINATING_SWITCH_IDENTIFICATION', 'String'
, 'optional, (but might be mandatory for interconnection and to '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20123, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.TERMINATING_SWITCH_IDENTIFICATION', 'String'
, 'optional, (but might be mandatory for interconnection and to '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20124, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.MS_CLASS_MARK', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20125, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.ROUTING_AREA', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20126, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.LOCATION_AREA_INDICATOR', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20127, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.CHARGING_ID', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20128, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.SGSN_ADDRESS', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20129, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.GGSN_ADDRESS', 'String', 'optional, (but might be mandatory for specific rating scenarios)'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20130, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.APN_ADDRESS', 'String', 'optional, (but might be mandatory for specific zoning scenarios,'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20131, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.NODE_ID', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20132, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.TRANS_ID', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20133, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.SUB_TRANS_ID', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20134, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.NETWORK_INITIATED_PDP', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20135, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.PDP_TYPE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20136, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.PDP_ADDRESS', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20137, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.PDP_REMOTE_ADDRESS', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20138, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.PDP_DYNAMIC_ADDRESS', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20139, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.DIAGNOSTICS', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20140, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.CELL_ID', 'String', 'optional, (but might be mandatory for specific rating '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20141, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.CHANGE_CONDITION', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20142, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.QOS_REQUESTED_PRECEDENCE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20143, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.QOS_REQUESTED_DELAY', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20144, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.QOS_REQUESTED_RELIABILITY', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20145, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.QOS_REQUESTED_PEAK_THROUGHPUT', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20146, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.QOS_REQUESTED_MEAN_THROUGHPUT', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20147, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.QOS_USED_PRECEDENCE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20148, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.QOS_USED_DELAY', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20149, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.QOS_USED_RELIABILITY', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20150, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.QOS_USED_PEAK_THROUGHPUT', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20151, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.QOS_USED_MEAN_THROUGHPUT', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20152, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.NETWORK_CAPABILITY', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20153, 'ALL_RATE', 'DETAIL.ASS_GPRS_EXT.SGSN_CHANGE', 'Integer', 'mandatory'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20154, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.RECORD_TYPE', 'String', 'mandatory, default=570'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20155, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.RECORD_NUMBER', 'Integer', 'mandatory, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20156, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.PORT_NUMBER', 'String', 'optional, (but might be mandatory for specific services in '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20157, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.DEVICE_NUMBER', 'String', 'optional, (e.g. IMEI)'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20158, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.SESSION_ID', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20159, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.RECORDING_ENTITY', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20160, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.TERMINAL_CLIENT_ID', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20161, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.TERMINAL_IP_ADDRESS', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20162, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.DOMAIN_URL', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20163, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.BEARER_SERVICE', 'String', 'optional, (but if defined the same value set as for the '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20164, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.HTTP_STATUS', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20165, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.WAP_STATUS', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20166, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.ACKNOWLEDGE_STATUS', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20167, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.ACKNOWLEDGE_TIME', 'Date', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20168, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.EVENT_NUMBER', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20169, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.GGSN_ADDRESS', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20170, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.SERVER_TYPE', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20171, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.CHARGING_ID', 'Integer', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20172, 'ALL_RATE', 'DETAIL.ASS_WAP_EXT.WAP_LOGIN', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20173, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.RECORD_TYPE', 'String', 'mandatory, default=700'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20174, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.RECORD_NUMBER', 'Integer', 'mandatory, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20175, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.SERVER_TYPE_OF_NUMBER', 'Integer', 'optional, but should be defaulted to ''0''. Could be used by some '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20176, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.SERVER_NUMBERING_PLAN', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20177, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.SERVER_ADDRESS', 'String', 'mandatory!, identifies the server interrogated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20178, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.SERVICE_LEVEL', 'Integer', 'mandatory! identifies the level of CAMEL service provided [0-3]'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20179, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.SERVICE_KEY', 'Integer', 'mandatory! identifies the CAMEL service Logic to be applied '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20180, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.DEFAULT_CALL_HANDLING_INDICATOR', 'Integer'
, 'optional, indicates whether or not a CAMEL call encountered'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20181, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.MSC_TYPE_OF_NUMBER', 'Integer', 'optional, but should be defaulted to ''0''. Could be used by some '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20182, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.MSC_NUMBERING_PLAN', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20183, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.MSC_ADDRESS', 'String', 'mandatory! identifies the MSC that generated the CAMEL reference'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20184, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.CAMEL_REFERENCE_NUMBER', 'String', 'mandatory! in association with the MSC_ADDRESS, provides a'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20185, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.CAMEL_INITIATED_CF_INDICATOR', 'Integer'
, 'optional, but should be defaulted to 0 (1=CAMEL call forwarding)'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20186, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.CAMEL_MODIFICATION_LIST', 'String', 'optional, comma separated string of integers'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20187, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.DEST_GSMW_TYPE_OF_NUMBER', 'Integer', 'optional, but should be defaulted to ''0''. Could be used by some '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20188, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.DEST_GSMW_NUMBERING_PLAN', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20189, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.DEST_GSMW_NUMBER', 'String', 'optional, will be used to identify CAMEL redirection destination'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20190, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.DEST_GSMW_NUMBER_ORIGINAL', 'String', 'optional, DEST_GSM_NUMBER as received (before normalization)'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20191, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.DEST_GPRS_APN_ADDRESS', 'String', 'optional, (but might be mandatory for specific zoning scenarios,'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20192, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.DEST_GPRS_PDP_REMOTE_ADDRESS', 'String', 'optional'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20193, 'ALL_RATE', 'DETAIL.ASS_CAMEL_EXT.CSE_INFORMATION', 'String', 'optional, the information downloaded by the CAMEL server'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20194, 'ALL_RATE', 'DETAIL.ASS_PIN.RECORD_TYPE', 'String', 'mandatory, default=900'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20195, 'ALL_RATE', 'DETAIL.ASS_PIN.RECORD_NUMBER', 'Integer', 'mandatory, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20196, 'ALL_RATE', 'DETAIL.ASS_PIN.ACCOUNT_POID', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20197, 'ALL_RATE', 'DETAIL.ASS_PIN.SERVICE_POID', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20198, 'ALL_RATE', 'DETAIL.ASS_PIN.ITEM_POID', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20199, 'ALL_RATE', 'DETAIL.ASS_PIN.PIN_TAX_LOCALES', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20200, 'ALL_RATE', 'DETAIL.ASS_PIN.PIN_TAX_SUPPLIER_ID', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20201, 'ALL_RATE', 'DETAIL.ASS_PIN.PIN_PROVIDER_ID', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20202, 'ALL_RATE', 'DETAIL.ASS_PIN.PIN_INVOICE_DATA', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20203, 'ALL_RATE', 'DETAIL.ASS_PIN.NUMBER_OF_BALANCE_PACKETS', 'Integer', 'mandatory, default=0'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20204, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_RESOURCE_ID', 'Integer', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20205, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_IMPACT_CATEGORY', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20206, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_PRODUCT_POID', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20207, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_GL_ID', 'Integer', 'mandatory-calculated, default=0'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20208, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_TAX_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20209, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_RATE_TAG', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20210, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_LINEAGE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20211, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_NODE_LOCATION', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20212, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_QUANTITY', 'Decimal', 'mandatory-calculated, default=0'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20213, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_AMOUNT', 'Decimal', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20214, 'ALL_RATE', 'DETAIL.ASS_PIN.BP.PIN_DISCOUNT', 'Decimal', 'mandatory-calculated, default=0'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20215, 'ALL_RATE', 'DETAIL.ASS_ZBD.RECORD_LENGTH', 'Integer', 'optional for backward compatibility'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20216, 'ALL_RATE', 'DETAIL.ASS_ZBD.RECORD_TYPE', 'String', 'mandatory, must be within the defined range (960-969)'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20217, 'ALL_RATE', 'DETAIL.ASS_ZBD.RECORD_NUMBER', 'Integer', 'mandatory, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20218, 'ALL_RATE', 'DETAIL.ASS_ZBD.CONTRACT_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20219, 'ALL_RATE', 'DETAIL.ASS_ZBD.SEGMENT_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20220, 'ALL_RATE', 'DETAIL.ASS_ZBD.CUSTOMER_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20221, 'ALL_RATE', 'DETAIL.ASS_ZBD.ACCOUNT_CODE', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20222, 'ALL_RATE', 'DETAIL.ASS_ZBD.SYSTEM_BRAND_CODE', 'String', 'mandatory-calculated, default=0'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20223, 'ALL_RATE', 'DETAIL.ASS_ZBD.SERVICE_CODE', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20224, 'ALL_RATE', 'DETAIL.ASS_ZBD.CUSTOMER_RATEPLAN_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20225, 'ALL_RATE', 'DETAIL.ASS_ZBD.SLA_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20226, 'ALL_RATE', 'DETAIL.ASS_ZBD.CUSTOMER_BILLCYCLE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20227, 'ALL_RATE', 'DETAIL.ASS_ZBD.CUSTOMER_CURRENCY', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20228, 'ALL_RATE', 'DETAIL.ASS_ZBD.CUSTOMER_TAXGROUP', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20229, 'ALL_RATE', 'DETAIL.ASS_ZBD.NUMBER_OF_ZONE_PACKETS', 'Integer', 'mandatory-calculated, default=1'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20230, 'ALL_RATE', 'DETAIL.ASS_ZBD.ZP.ZONEMODEL_CODE', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20231, 'ALL_RATE', 'DETAIL.ASS_ZBD.ZP.ZONE_RESULT_VALUE_WS', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20232, 'ALL_RATE', 'DETAIL.ASS_ZBD.ZP.ZONE_RESULT_VALUE_RT', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20233, 'ALL_RATE', 'DETAIL.ASS_ZBD.ZP.DISTANCE', 'Integer', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20234, 'ALL_RATE', 'DETAIL.ASS_ZBD.ZP.INTERN_ZONE_MODEL', 'Integer', 'mandatory-calculated - keeps the internal zonemodel-id to be '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20235, 'ALL_RATE', 'DETAIL.ASS_ZBD.ZP.INTERN_APN_GROUP', 'String', 'mandatory-calculated - keeps the internal apn_group-code to be '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20236, 'ALL_RATE', 'DETAIL.ASS_CBD.RECORD_LENGTH', 'Integer', 'optional for backward compatibility'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20237, 'ALL_RATE', 'DETAIL.ASS_CBD.RECORD_TYPE', 'String', 'mandatory, must be within the defined range (970-998)'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20238, 'ALL_RATE', 'DETAIL.ASS_CBD.RECORD_NUMBER', 'Integer', 'mandatory, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20239, 'ALL_RATE', 'DETAIL.ASS_CBD.CONTRACT_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20240, 'ALL_RATE', 'DETAIL.ASS_CBD.SEGMENT_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20241, 'ALL_RATE', 'DETAIL.ASS_CBD.CUSTOMER_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20242, 'ALL_RATE', 'DETAIL.ASS_CBD.ACCOUNT_CODE', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20243, 'ALL_RATE', 'DETAIL.ASS_CBD.SYSTEM_BRAND_CODE', 'String', 'mandatory-calculated, default=0'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20244, 'ALL_RATE', 'DETAIL.ASS_CBD.SERVICE_CODE', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20245, 'ALL_RATE', 'DETAIL.ASS_CBD.CUSTOMER_RATEPLAN_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20246, 'ALL_RATE', 'DETAIL.ASS_CBD.SLA_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20247, 'ALL_RATE', 'DETAIL.ASS_CBD.CUSTOMER_BILLCYCLE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20248, 'ALL_RATE', 'DETAIL.ASS_CBD.CUSTOMER_CURRENCY', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20249, 'ALL_RATE', 'DETAIL.ASS_CBD.CUSTOMER_TAXGROUP', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20250, 'ALL_RATE', 'DETAIL.ASS_CBD.NUMBER_OF_CHARGE_PACKETS', 'Integer', 'mandatory-calculated, default=1'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20251, 'ALL_RATE', 'DETAIL.ASS_CBD.INTERN_CALC_MODE', 'Integer', 'mandatory-calculated - keeps the internal network-model '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20252, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.RATEPLAN_CODE', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20253, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.RATEPLAN_TYPE', 'String', 'mandatory!-calculated, default=''R'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20254, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.ZONEMODEL_CODE', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20255, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.SERVICE_CODE_USED', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20256, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.SERVICE_CLASS_USED', 'String', 'mandatory-calculated, default=''*'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20257, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.IMPACT_CATEGORY', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20258, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.DISTANCE', 'Integer', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20259, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.TIMEMODEL_CODE', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20260, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.TIMEZONE_CODE', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20261, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.DAY_CODE', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20262, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.TIME_INTERVAL_CODE', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20263, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.PRICEMODEL_CODE', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20264, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.PRICEMODEL_TYPE', 'String', 'mandatory-calculated, default=''S'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20265, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.RESOURCE', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20266, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.RUMGROUP', 'String', 'mandatory!-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20267, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.RUM', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20268, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.NETWORK_OPERATOR_CODE', 'String', 'optional-calculated, only mandatory for interconnection rating'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20269, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.NETWORK_OPERATOR_BILLINGTYPE', 'String', 'optional-calculated, only mandatory for interconnection rating'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20270, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.CHARGE_TYPE', 'String', 'mandatory-calculated, default=''N'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20271, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.TRUNK_USED', 'String', 'optional-calculated, only mandatory for interconnection rating'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20272, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.POI_USED', 'String', 'optional-calculated, only mandatory for interconnection rating'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20273, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.PRODUCTCODE_USED', 'String', 'optional-calculated, only mandatory for interconnection rating'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20274, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.CHARGING_START_TIMESTAMP', 'Date', 'mandatory!-calculated - contains a partial timestamp in case of '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20275, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.CHARGEABLE_QUANTITY_VALUE', 'Decimal', 'optional, set by input or rating, default=ROUNDED_QUANTITY_VALUE'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20276, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.ROUNDED_QUANTITY_VALUE', 'Decimal', 'mandatory!-calculated - contains a partial value in case of '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20277, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.ROUNDED_QUANTITY_UOM', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20278, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.EXCHANGE_RATE', 'Decimal', 'optional-calculated, default=''1'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20279, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.EXCHANGE_CURRENCY', 'String', 'optional, but should be defaulted to CHARGED_AMOUNT_CURRENCY'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20280, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.CHARGED_CURRENCY_TYPE', 'String', 'mandatory-calculated, default=''R'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20281, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.CHARGED_AMOUNT_VALUE', 'Decimal', 'mandatory!-calculated - contains a partial value in case of '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20282, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.CHARGED_AMOUNT_CURRENCY', 'String', 'mandatory-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20283, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.CHARGED_TAX_TREATMENT', 'String', 'mandatory-calculated, default=''N'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20284, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.CHARGED_TAX_RATE', 'Integer', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20285, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.CHARGED_TAX_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20286, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.USAGE_GL_ACCOUNT_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20287, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.REVENUE_GROUP_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20288, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.DISCOUNTMODEL_CODE', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20289, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.GRANTED_DISCOUNT_AMOUNT_VALUE', 'Decimal', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20290, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.GRANTED_DISCOUNT_QUANTITY_VALUE', 'Decimal'
, 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20291, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.GRANTED_DISCOUNT_QUANTITY_UOM', 'String', 'optional-calculated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20292, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_RATEPLAN', 'String', 'mandatory-calculated - keeps the internal rateplan-ids '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20293, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_RATEPLAN_VERSION', 'Integer', 'mandatory-calculated - keeps the internal '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20294, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_ZONE_MODEL', 'Integer', 'mandatory-calculated - keeps the internal zone_model-id which '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20295, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_APN_GROUP', 'String', 'mandatory-calculated - keeps the internal apn_group-code which '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20296, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_ORIGIN_NUM_ZONE', 'String', 'mandatory-calculated - keeps the internal a_number which should '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20297, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_DESTIN_NUM_ZONE', 'String', 'mandatory-calculated - keeps the internal b_number which should '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20298, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_FIX_COST', 'Decimal', 'mandatory-calculated - keeps an internal fix-cost-price for '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20299, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_DISCOUNT_MODEL', 'Integer', 'mandatory-calculated - keeps the internal discount_model-id '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20300, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_DISCOUNT_ACCOUNT', 'String', 'mandatory-calculated - keeps the internal discount_account-id '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20301, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_HOME_CURRENCY', 'String', 'optional-calculated - keeps the home-currency for'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20302, 'ALL_RATE', 'DETAIL.ASS_CBD.CP.INTERN_BILLING_CURRENCY', 'String', 'optional-calculated - keeps the billing-currency for'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20303, 'ALL_RATE', 'TRAILER.RECORD_LENGTH', 'Integer', 'optional for backward compatibility'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20304, 'ALL_RATE', 'TRAILER.RECORD_TYPE', 'String', 'mandatory, must be set to ''090'''); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20305, 'ALL_RATE', 'TRAILER.RECORD_NUMBER', 'Integer', 'mandatory, auto-generated'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20306, 'ALL_RATE', 'TRAILER.SENDER', 'String', 'optional, but should be defaulted with the same value as in '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20307, 'ALL_RATE', 'TRAILER.RECIPIENT', 'String', 'optional, but should be defaulted with the same value same as in'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,
DESCRIPTION ) VALUES ( 
20308, 'ALL_RATE', 'TRAILER.SEQUENCE_NUMBER', 'Integer', 'calculated (only, if a sequence-check or -generation had been '); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION ) VALUES ( 
20441, 'ALL_RATE', 'DETAIL.ASS_ROAMING_EXT.RECIPIENT', 'String', 'mandatory, It will contain the PLMN of the operater who receives the TAP file'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION) VALUES ( 
20440, 'ALL_RATE', 'DETAIL.ASS_ROAMING_EXT.SENDER', 'String', 'mandatory, It will contain the PLMN of the operater who sends the TAP file'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,DESCRIPTION ) VALUES ( 
20442, 'ALL_RATE', 'DETAIL.PROFILE_LABEL_LIST', 'String', 'optional,It will contain the matching label levels of the profile'); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,DESCRIPTION ) VALUES ( 
20443, 'ALL_RATE', 'DETAIL.ASS_SUSPENSE_EXT.PIPELINE_NAME', 'String','It contains the pipeline name which suspends the edr');
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,DESCRIPTION ) VALUES (
20444, 'ALL_RATE', 'DETAIL.DROPPED_CALL_QUANTITY', 'Decimal','optional, It will contain the quantity of the dropped call');
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE,DESCRIPTION ) VALUES (
20445, 'ALL_RATE', 'DETAIL.DROPPED_CALL_STATUS', 'String','optional, It will contain the dropped call status');
commit;
