INSERT INTO IFW_USAGECLASS_MAP ( MAP_GROUP, RANK, EXT_USAGECLASS, USAGETYPE, ZONE_WS, TARIFFCLASS,
TARIFFSUBCLASS, RECORDTYPE, CONNECTTYPE, CONNECTSUBTYPE, SS_PACKET, APN_ADDRESS, TRANSIT_AREACODE,
NAME, INT_USAGECLASS ) VALUES ( 
'ALL_RATE', 1, '(M|m).*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*'
, 'Simple Mapping to Mailbox Inquiry', 'MBI'); 
INSERT INTO IFW_USAGECLASS_MAP ( MAP_GROUP, RANK, EXT_USAGECLASS, USAGETYPE, ZONE_WS, TARIFFCLASS,
TARIFFSUBCLASS, RECORDTYPE, CONNECTTYPE, CONNECTSUBTYPE, SS_PACKET, APN_ADDRESS, TRANSIT_AREACODE,
NAME, INT_USAGECLASS ) VALUES ( 
'ALL_RATE', 2, '(C|c)onf.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*'
, '.*', 'Simple Mapping to Conference Call', 'CONF'); 
commit;
 
