INSERT INTO IFW_DAYCODE ( DAYCODE, CODE, NAME, DATEDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY,
FRIDAY, SATURDAY, SUNDAY, HOLIDAY ) VALUES ( 
20001, 'WEEKDAY', 'Weekdays (Mon-Fri)', NULL, 1, 1, 1, 1, 1, 0, 0, 0); 
INSERT INTO IFW_DAYCODE ( DAYCODE, CODE, NAME, DATEDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY,
FRIDAY, SATURDAY, SUNDAY, HOLIDAY ) VALUES ( 
20002, 'WEEKEND', 'Weekends (Sat-Sun+Hol)', NULL, 0, 0, 0, 0, 0, 1, 1, 1); 
INSERT INTO IFW_DAYCODE ( DAYCODE, CODE, NAME, DATEDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY,
FRIDAY, SATURDAY, SUNDAY, HOLIDAY ) VALUES ( 
20003, 'ALLDAYS', 'All Days (Mon-Sun+Hol)', NULL, 1, 1, 1, 1, 1, 1, 1, 1); 
commit;
 
