INSERT INTO IFW_SERVICECLASS ( SERVICECODE, SERVICECLASS, NAME ) VALUES ( 
'FAX', 'DEF', 'Default ServiceClass for FAX'); 
INSERT INTO IFW_SERVICECLASS ( SERVICECODE, SERVICECLASS, NAME ) VALUES ( 
'TEL', 'DEF', 'Default ServiceClass for TEL'); 
INSERT INTO IFW_SERVICECLASS ( SERVICECODE, SERVICECLASS, NAME ) VALUES ( 
'GPRSI', 'DEF', 'Default ServiceClass for GPRSI'); 
INSERT INTO IFW_SERVICECLASS ( SERVICECODE, SERVICECLASS, NAME ) VALUES (
'GPRST', 'DEF', 'Default ServiceClass for GPRST');
INSERT INTO IFW_SERVICECLASS ( SERVICECODE, SERVICECLASS, NAME ) VALUES ( 
'SMS', 'DEF', 'Default ServiceClass for SMS'); 
INSERT INTO IFW_SERVICECLASS ( SERVICECODE, SERVICECLASS, NAME ) VALUES ( 
'WAP', 'DEF', 'Default ServiceClass for WAP'); 
INSERT INTO IFW_SERVICECLASS ( SERVICECODE, SERVICECLASS, NAME ) VALUES ( 
'DATA', 'DEF', 'Default ServiceClass for DATA'); 
commit;
 
