update IFW_SERVICE set PIN_SERVICETYPE = '/service/telco/gsm/telephony', DEF_GLACCOUNT = '1420', RANK = 1 
where SERVICECODE = 'TEL';
update IFW_SERVICE set PIN_SERVICETYPE = '/service/ip/gprs', DEF_GLACCOUNT = '1450', RANK = 3, SERVICECODE = 'GPRSI'
where SERVICECODE = 'GPRS';
update IFW_SERVICE set PIN_SERVICETYPE = '/service/wap/interactive', DEF_GLACCOUNT = '1460', RANK = 4 
where SERVICECODE = 'WAP';
update IFW_SERVICE set PIN_SERVICETYPE = '/service/telco/gsm/sms', DEF_GLACCOUNT = '1430', RANK = 2 
where SERVICECODE = 'SMS';

INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'DATA', 'GSM Data Service', 5, 'B', 'DURATION', '1420', NULL, NULL, 1, '/service/telco/gsm/data');
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'FAX', 'GSM Fax Service', 6, 'B', 'DURATION', '1420', NULL, NULL, 1, '/service/telco/gsm/fax');
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'*', 'dummy service', 99, 'L', 'DURATION', '1420', NULL, NULL, 1, '/service'); 
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE) VALUES ( 
'SET_I', 'incollect settlement', 1, 'L', 'DURATION', '1420', NULL, NULL, 1, '/service/settlement/roaming/incollect'); 
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'SET_O', 'outcollect settlement', 1, 'L', 'DURATION', '1420', NULL, NULL, 1, '/service/settlement/roaming/outcollect'); 
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES (
'GPRST', 'General Packet Radio Service', 1, 'B', 'TOTAL', '1450', NULL, NULL, 1, '/service/telco/gprs');
commit;
