INSERT INTO IFW_DSCMDL_VER ( DISCOUNTMODEL, VERSION, VALID_FROM,
STATUS ) VALUES ( 
(SELECT DISCOUNTMODEL FROM IFW_DISCOUNTMODEL WHERE CODE = 'DM10%OFF'), 1,
TO_Date( '01/01/1999 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'A'); 
INSERT INTO IFW_DSCMDL_VER ( DISCOUNTMODEL, VERSION, VALID_FROM,
STATUS ) VALUES ( 
(SELECT DISCOUNTMODEL FROM IFW_DISCOUNTMODEL WHERE CODE = 'DMFMALL'), 1,
TO_Date( '01/01/1999 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'A'); 
INSERT INTO IFW_DSCMDL_VER ( DISCOUNTMODEL, VERSION, VALID_FROM,
STATUS ) VALUES ( 
(SELECT DISCOUNTMODEL FROM IFW_DISCOUNTMODEL WHERE CODE = 'CS10%OFF'), 1,
TO_Date( '01/01/2003 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'A'); 
commit;
