INSERT INTO IFW_DSCTRIGGER ( DISCOUNTTRIGGER, CODE, NAME ) VALUES ( 
IFW_SEQ_DISCOUNTTRIGGER.NEXTVAL, 'DT10%OFF', 'Discount Trigger For Taking 10% Off'); 
INSERT INTO IFW_DSCTRIGGER ( DISCOUNTTRIGGER, CODE, NAME ) VALUES ( 
IFW_SEQ_DISCOUNTTRIGGER.NEXTVAL, 'DTFMALL', 'Discount Trigger For Free Minutes'); 
INSERT INTO IFW_DSCTRIGGER ( DISCOUNTTRIGGER, CODE, NAME ) VALUES ( 
IFW_SEQ_DISCOUNTTRIGGER.NEXTVAL, 'CT10%OFF', 'Charge Share Trigger For Taking 10% Off'); 
commit;
 
