INSERT INTO IFW_ICPRODUCT ( ICPRODUCT, NAME, VALID_FROM, STATUS ) VALUES ( 
'OPRT2', 'OPRT2',  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'A'); 
INSERT INTO IFW_ICPRODUCT ( ICPRODUCT, NAME, VALID_FROM, STATUS ) VALUES ( 
'OPRT1', 'OPRT1',  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'A'); 

INSERT INTO IFW_ICPRODUCT_GRP ( NETWORKMODEL, ICPRODUCT_GROUP, NAME ) VALUES ( 
1, 'Standard', 'Standard'); 

INSERT INTO IFW_ICPRODUCT_RATE ( NETWORKMODEL, NO, ICPRODUCT, VALID_FROM, ZONE_DIRECTION, ZONE_TYPE,
BILL_DIRECTION, RATEPLAN, ALT_RATEPLAN, FIXCOST, PIN_LOGIN_ALIAS ) VALUES ( 
1, 3, 'OPRT2',  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), '0'
, 'N', 'I', 20001, NULL, NULL, NULL); 
INSERT INTO IFW_ICPRODUCT_RATE ( NETWORKMODEL, NO, ICPRODUCT, VALID_FROM, ZONE_DIRECTION, ZONE_TYPE,
BILL_DIRECTION, RATEPLAN, ALT_RATEPLAN, FIXCOST, PIN_LOGIN_ALIAS ) VALUES ( 
1, 2, 'OPRT1',  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), '0'
, 'N', 'I', 20001, NULL, NULL, NULL); 

INSERT INTO IFW_ICPRODUCT_CNF ( NETWORKMODEL, ICPRODUCT_GROUP, RANK, VALID_FROM, NAME,
SOURCE_NETWORK, DESTIN_NETWORK, ORIGIN_AREACODE, DESTIN_AREACODE, TRANSIT_AREACODE, RECORDTYPE,
SERVICECODE, SERVICECLASS, USAGECLASS, ICPRODUCT ) VALUES ( 
1, 'Standard', 1,  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'Standard'
, 'OPRT2', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'OPRT2'); 
INSERT INTO IFW_ICPRODUCT_CNF ( NETWORKMODEL, ICPRODUCT_GROUP, RANK, VALID_FROM, NAME,
SOURCE_NETWORK, DESTIN_NETWORK, ORIGIN_AREACODE, DESTIN_AREACODE, TRANSIT_AREACODE, RECORDTYPE,
SERVICECODE, SERVICECLASS, USAGECLASS, ICPRODUCT ) VALUES ( 
1, 'Standard', 2,  TO_Date( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'Standard'
, 'OPRT1', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'OPRT1'); 
COMMIT;
