INSERT INTO IFW_DSCTRIGGER ( DISCOUNTTRIGGER, CODE, NAME ) VALUES (
300001, 'DT_MOSTCL', 'Trigger For Most Called Discount');

INSERT INTO IFW_DSCCONDITION ( DISCOUNTCONDITION, DISCOUNTTRIGGER, 
COND_EXPRESSION, COND_OPERATOR, CONDITION_VALUE ) VALUES (
300001, 300001, 'EVAL("getMostCalledDuration")', 'GT', 100);

INSERT INTO IFW_DISCOUNTMODEL ( DISCOUNTMODEL, CODE, NAME, CHARGESHARE_FLAG ) 
VALUES ( 300001, 'DM_MOSTCL', 'Discount Model for 10% off Most Called Numbers',
 0);

INSERT INTO IFW_DSCMDL_VER ( DISCOUNTMODEL, VERSION, VALID_FROM, STATUS ) 
VALUES ( 300001, 1,  TO_Date( '01/01/2003 12:00:00 AM', 
'MM/DD/YYYY HH:MI:SS AM'), 'A');

INSERT INTO IFW_DISCOUNTMASTER ( DISCOUNTMASTER, CODE, NAME ) VALUES (
300001, 'DMA_MOSTCL', 'Discount Master For Most Called');

INSERT INTO IFW_DISCOUNTDETAIL ( DISCOUNTMASTER, RANK, VALID_FROM, VALID_TO,
TIME_FROM, TIME_TO, ZONEMODEL, IMPACT_CATEGORY, SERVICECODE, SERVICECLASS,
TIMEMODEL, TIMEZONE, PRICEMODEL, RESSOURCE, RUM, RECORDTYPE, RATE_PLAN,
RATE_TAG, GLID ) VALUES (
300001, 2, '19990101', NULL, NULL, NULL, '.*', '.*' , '.*', '.*', '.*',
'.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*');

INSERT INTO IFW_DISCOUNTRULE ( DISCOUNTRULE, CODE, NAME, DISCOUNTMASTER, 
DRUM_EXPRESSION, RULE_TYPE, DRUM_TYPE ) VALUES ( 300001, 'DR_MOSTCL', 
'Discount Rule for Most Called', 300001, '1', '1', 'C');

INSERT INTO IFW_DISCOUNTSTEP ( DISCOUNTSTEP, CODE, DISCOUNTRULE, RANK, 
THRESHOLD_FROM, THRESHOLD_TO, PRORATE_PURCHASE, PRORATE_CANCEL ) VALUES (
300001, 'DS_MOSTCL', 300001, 3, 0, 0, 702, 702);

INSERT INTO IFW_DSCBALIMPACT ( DISCOUNTBALIMPACT, DISCOUNTSTEP, 
GRANT_PRORATEDBEAT, GRANT_UNITS, GRANT_BEAT, BASE_EXPRESSION, EVENT_BALANCE_ID,
DISCOUNT_OWNER_FLAG, RESOURCE_ID, GRANT_PERIOD_OFFSET, DISCOUNT_TYPE ) VALUES (
300001, 300001, 0, -0.1, 0, 'EVAL("getMostCalledCost")', 0, 0, 978, -1, 'P');

INSERT INTO IFW_DSCMDL_CNF ( DISCOUNTCONFIG, DISCOUNTMODEL, VERSION, RANK, 
DISCOUNTTRIGGER, DISCOUNTRULE, DSC_MODE ) VALUES ( 300001, 300001, 1, 3, 
300001, 300001, 0);

commit;
