INSERT INTO IFW_TIMEZONE ( TIMEZONE, CODE, NAME ) VALUES ( 
20001, 'WEEKPEAK', 'Weekdays Peak'); 
INSERT INTO IFW_TIMEZONE ( TIMEZONE, CODE, NAME ) VALUES ( 
20002, 'WEEKOFF1', 'Weekdays OffPeak 1'); 
INSERT INTO IFW_TIMEZONE ( TIMEZONE, CODE, NAME ) VALUES ( 
20003, 'WEEKOFF2', 'Weekdays OffPeak 2'); 
INSERT INTO IFW_TIMEZONE ( TIMEZONE, CODE, NAME ) VALUES ( 
20004, 'WEEKOFF3', 'Weekdays OffPeak 3'); 
INSERT INTO IFW_TIMEZONE ( TIMEZONE, CODE, NAME ) VALUES ( 
20005, 'WENDPEAK', 'Weekend Peak'); 
INSERT INTO IFW_TIMEZONE ( TIMEZONE, CODE, NAME ) VALUES ( 
20006, 'WENDOFF', 'Weekend OffPeak'); 
INSERT INTO IFW_TIMEZONE ( TIMEZONE, CODE, NAME ) VALUES ( 
20007, 'FLAT', 'Flat'); 
commit;
 
