INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'RUM', 'SND', 'I', 20055); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'RUM', 'REC', 'I', 20057); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'UOM', 'DUR.SEC', 'I', 20054); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'UOM', 'SND.BYT', 'I', 20056); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'UOM', 'REC.BYT', 'I', 20058); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'UniData_CustA', 'TEL', 'I', 20032); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'UniData_CustA', 'GPRSI', 'I', 20032);
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES (
'ALL_RATE', 'UniData_CustA', 'GPRST', 'I', 20032);
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'UniData_CustA', 'WAP', 'I', 20032); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'RUM', 'DUR', 'I', 20053); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'UniData_CustA', 'SMS', 'I', 20032); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'UniData_CustA', 'DATA', 'I', 20032); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,
FIELD_ID ) VALUES ( 
'ALL_RATE', 'UniData_CustA', 'FAX', 'I', 20032); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE, FIELD_ID) VALUES ( 
'ALL_RATE', 'UniData_CustA', 'SET_O', 'I', 20441); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE, FIELD_ID ) VALUES ( 
'ALL_RATE', 'UniData_CustA', 'SET_I', 'I', 20440);
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,FIELD_ID ) VALUES ( 
'ALL_RATE', 'ServiceOutputSplit', 'INTERN_SERVICE_CODE', 'I', 20045); 
INSERT INTO IFW_ALIAS_MAP ( EDRC_DESC, REFERENCE, KEY_ID, TYPE,FIELD_ID ) VALUES ( 
'ALL_RATE', 'PipelineSplit', 'SOURCE_NETWORK', 'I', 20443);
commit;
