INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1430', 'National Airtime SMS', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1431', 'International Airtime SMS', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1440', 'National Airtime other GSM', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1441', 'International Airtime other GSM', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1450', 'National Usage GPRS ', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1420', 'National Airtime Telephony', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1421', 'International Airtime Telephony', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1451', 'International Usage GPRS', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1501', 'Int. Incomming Roaming GSM', 'ZERO', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1502', 'Int. Outgoing Roaming GSM', 'ZERO', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1460', 'National Usage other Services', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1461', 'International Usage other Services', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1510', 'National VAS', 'NORM', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1511', 'International VAS', 'REDUC', 'R'); 
INSERT INTO IFW_GLACCOUNT ( GLACCOUNT, NAME, TAXCODE, GLA_TYPE ) VALUES ( 
'1600', 'GSM Sample Usage', 'NORM', 'R'); 
commit;
 
