INSERT INTO IFW_DSCMDL_CNF ( DISCOUNTCONFIG, DISCOUNTMODEL, VERSION, RANK, 
DISCOUNTTRIGGER, DISCOUNTRULE, DSC_MODE ) VALUES ( 
IFW_SEQ_DISCOUNTCONFIG.NEXTVAL, (SELECT DISCOUNTMODEL FROM IFW_DISCOUNTMODEL WHERE CODE ='DM10%OFF'), 1, 1,
(SELECT DISCOUNTTRIGGER FROM IFW_DSCTRIGGER WHERE CODE ='DT10%OFF'),
(SELECT DISCOUNTRULE FROM IFW_DISCOUNTRULE WHERE CODE ='DR10%OFF'), 0); 
INSERT INTO IFW_DSCMDL_CNF ( DISCOUNTCONFIG, DISCOUNTMODEL, VERSION, RANK, 
DISCOUNTTRIGGER, DISCOUNTRULE, DSC_MODE ) VALUES ( 
IFW_SEQ_DISCOUNTCONFIG.NEXTVAL,(SELECT DISCOUNTMODEL FROM IFW_DISCOUNTMODEL WHERE CODE ='DMFMALL'),1,2,
(SELECT DISCOUNTTRIGGER FROM IFW_DSCTRIGGER WHERE CODE ='DTFMALL'),
(SELECT DISCOUNTRULE FROM IFW_DISCOUNTRULE WHERE CODE ='DRFMALL'),0); 
INSERT INTO IFW_DSCMDL_CNF ( DISCOUNTCONFIG, DISCOUNTMODEL, VERSION, RANK, 
DISCOUNTTRIGGER, DISCOUNTRULE, DSC_MODE ) VALUES ( 
IFW_SEQ_DISCOUNTCONFIG.NEXTVAL, (SELECT DISCOUNTMODEL FROM IFW_DISCOUNTMODEL WHERE CODE ='CS10%OFF'), 1, 3,
(SELECT DISCOUNTTRIGGER FROM IFW_DSCTRIGGER WHERE CODE ='CT10%OFF'),
(SELECT DISCOUNTRULE FROM IFW_DISCOUNTRULE WHERE CODE ='CR10%OFF'), 0); 
commit;
 
