INSERT INTO IFW_DISCOUNTSTEP ( DISCOUNTSTEP, CODE, DISCOUNTRULE, RANK,
THRESHOLD_FROM, THRESHOLD_TO, PRORATE_PURCHASE, PRORATE_CANCEL )
VALUES ( 
IFW_SEQ_DISCOUNTSTEP.NEXTVAL, 'DS100000',(SELECT DISCOUNTRULE FROM IFW_DISCOUNTRULE WHERE CODE ='DR10%OFF') , 1, 0, 0, 702, 702); 
INSERT INTO IFW_DISCOUNTSTEP ( DISCOUNTSTEP, CODE, DISCOUNTRULE, RANK,
THRESHOLD_FROM, THRESHOLD_TO, PRORATE_PURCHASE, PRORATE_CANCEL )
VALUES ( 
IFW_SEQ_DISCOUNTSTEP.NEXTVAL, 'DS100001',(SELECT DISCOUNTRULE FROM IFW_DISCOUNTRULE WHERE CODE ='DRFMALL') , 2, 0, 'Bal(1000095)', 
702, 702); 
INSERT INTO IFW_DISCOUNTSTEP ( DISCOUNTSTEP, CODE, DISCOUNTRULE, RANK,
THRESHOLD_FROM, THRESHOLD_TO, PRORATE_PURCHASE, PRORATE_CANCEL )
VALUES ( 
IFW_SEQ_DISCOUNTSTEP.NEXTVAL, 'CS100002',(SELECT DISCOUNTRULE FROM IFW_DISCOUNTRULE WHERE CODE ='CR10%OFF') , 3, 0, 0, 702, 702); 
commit; 
