INSERT INTO IFW_SEQCHECK ( SEQUENCE_NAME, KEY_ID, SEQ_NUMBER, SEQ_ORIGNUMBER, SEQ_GAPNUMBERS,
SEQ_OFFSET, SEQ_MAXSEQUENCE, SEQ_MAXOFFSET, SEQ_MINSEQUENCE, SEQ_MINOFFSET ) VALUES ( 
'SEQ_CHECK_TAPIN', 'OPRT1', 0, 0, '-1', 0, 99999, 99999, 0, 0); 
INSERT INTO IFW_SEQCHECK ( SEQUENCE_NAME, KEY_ID, SEQ_NUMBER, SEQ_ORIGNUMBER, SEQ_GAPNUMBERS,
SEQ_OFFSET, SEQ_MAXSEQUENCE, SEQ_MAXOFFSET, SEQ_MINSEQUENCE, SEQ_MINOFFSET ) VALUES ( 
'SEQ_CHECK_TAPIN', 'OPRT2', 0, 0, '-1', 0, 99999, 99999, 0, 0); 
INSERT INTO IFW_SEQCHECK ( SEQUENCE_NAME, KEY_ID, SEQ_NUMBER, SEQ_ORIGNUMBER, SEQ_GAPNUMBERS,
SEQ_OFFSET, SEQ_MAXSEQUENCE, SEQ_MAXOFFSET, SEQ_MINSEQUENCE, SEQ_MINOFFSET ) VALUES ( 
'SEQ_GEN_RAPOUT', 'OPRT1', 0, 0, '-1', 0, 99999, 99999, 0, 0); 
INSERT INTO IFW_SEQCHECK ( SEQUENCE_NAME, KEY_ID, SEQ_NUMBER, SEQ_ORIGNUMBER, SEQ_GAPNUMBERS,
SEQ_OFFSET, SEQ_MAXSEQUENCE, SEQ_MAXOFFSET, SEQ_MINSEQUENCE, SEQ_MINOFFSET ) VALUES ( 
'SEQ_GEN_RAPOUT', 'OPRT2', 0, 0, '-1', 0, 99999, 99999, 0, 0); 
INSERT INTO IFW_SEQCHECK ( SEQUENCE_NAME, KEY_ID, SEQ_NUMBER, SEQ_ORIGNUMBER, SEQ_GAPNUMBERS,
SEQ_OFFSET, SEQ_MAXSEQUENCE, SEQ_MAXOFFSET, SEQ_MINSEQUENCE, SEQ_MINOFFSET ) VALUES ( 
'SEQ_GEN_TAPOUT_OPRT1', '-1', 0, 0, '-1', 0, 99999, 99999, 0, 0); 
INSERT INTO IFW_SEQCHECK ( SEQUENCE_NAME, KEY_ID, SEQ_NUMBER, SEQ_ORIGNUMBER, SEQ_GAPNUMBERS,
SEQ_OFFSET, SEQ_MAXSEQUENCE, SEQ_MAXOFFSET, SEQ_MINSEQUENCE, SEQ_MINOFFSET ) VALUES ( 
'SEQ_GEN_TAPOUT_OPRT2', '-1', 0, 0, '-1', 0, 99999, 99999, 0, 0); 
INSERT INTO IFW_SEQCHECK ( SEQUENCE_NAME, KEY_ID, SEQ_NUMBER, SEQ_ORIGNUMBER, SEQ_GAPNUMBERS,
SEQ_OFFSET, SEQ_MAXSEQUENCE, SEQ_MAXOFFSET, SEQ_MINSEQUENCE, SEQ_MINOFFSET ) VALUES (
'SEQ_GEN_NRTRDEOUT_OPRT1', '-1', 0, 0, '-1', 0, 9999999, 9999999, 0, 0);
INSERT INTO IFW_SEQCHECK ( SEQUENCE_NAME, KEY_ID, SEQ_NUMBER, SEQ_ORIGNUMBER, SEQ_GAPNUMBERS,
SEQ_OFFSET, SEQ_MAXSEQUENCE, SEQ_MAXOFFSET, SEQ_MINSEQUENCE, SEQ_MINOFFSET ) VALUES (
'SEQ_GEN_NRTRDEOUT_OPRT2', '-1', 0, 0, '-1', 0, 9999999, 9999999, 0, 0);
commit;
