INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'NAT_CUG', 'NAT_CUG', 1, 'National ClosedUserGroup Calls'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'NAT_CONF', 'NAT_CONF', 1, 'National Conference Call'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'NAT_FIX', 'NAT_FIX', 0, 'National Usage Mobile-to-Fixed (within 0049)'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'NAT_MBI', 'NAT_MBI', 1, 'National Mailbox Inquiry'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'WORLD_CONF', 'WORLD_CONF', 1, 'International Conference Call'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'IN_ROAM', 'IN_ROAM', 0, 'Incomming Roaming'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'NAT_MOB', 'NAT_MOB', 0, 'National Usage Mobile-to-Mobile (within 004917)'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'WORLD1', 'WORLD1', 0, 'International Usage 1 (standard world countries outside 0049)'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'WORLD2', 'WORLD2', 0, 'International Usage 2 (expensive world countries outside 0049)'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'EUROPE', 'EUROPE', 0, 'Usage within Europe (outside 0049)'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'NAT_FF', 'NAT_FF', 1, 'National Friends u.Family Calls'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'OUT_ROAM', 'OUT_ROAM', 0, 'Outgoing Roaming'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'FREE', 'FREE', 0, 'Free Phone Calls (e.g. Emergency or Toll Free)'); 
INSERT INTO IFW_IMPACT_CAT ( IMPACT_CATEGORY, RESULT, TYPE,
NAME ) VALUES ( 
'NAT_PREM', 'NAT_PREM', 0, 'National Premium Calls'); 
commit;
 
