INSERT INTO IFW_USC_MAP ( USC_GROUP, ZONEMODEL, RANK, VALID_FROM, VALID_TO, TIME_FROM,
TIME_TO, QUANTITY_VALUE, MIN_WS_AMOUNT, MAX_WS_AMOUNT, USAGECLASS, USAGETYPE, SERVICECODE,
SERVICECLASS, ZONE_WS, ZONE_RT, NEW_USAGETYPE, IMPACT_CATEGORY_WS, IMPACT_CATEGORY_RT,
NAME ) VALUES ( 
'ALL_RATE', 20000, 3, '19990101', NULL, NULL, NULL, NULL, NULL, NULL, 'CONF', '.*'
, 'TEL', '.*', '.*', '!(WORLD.|EUROPE|NAT_PREM)', NULL, 'NAT_CONF', 'NAT_CONF', 'National Conference Call'); 
INSERT INTO IFW_USC_MAP ( USC_GROUP, ZONEMODEL, RANK, VALID_FROM, VALID_TO, TIME_FROM,
TIME_TO, QUANTITY_VALUE, MIN_WS_AMOUNT, MAX_WS_AMOUNT, USAGECLASS, USAGETYPE, SERVICECODE,
SERVICECLASS, ZONE_WS, ZONE_RT, NEW_USAGETYPE, IMPACT_CATEGORY_WS, IMPACT_CATEGORY_RT,
NAME ) VALUES ( 
'ALL_RATE', 20000, 1, '19990101', NULL, NULL, NULL, NULL, NULL, NULL, 'MBI', '.*'
, 'TEL', '.*', '.*', '(NAT_MOB|NAT_FIX)', NULL, 'NAT_MBI', 'NAT_MBI', 'National Mailbox Inquirey'); 
INSERT INTO IFW_USC_MAP ( USC_GROUP, ZONEMODEL, RANK, VALID_FROM, VALID_TO, TIME_FROM,
TIME_TO, QUANTITY_VALUE, MIN_WS_AMOUNT, MAX_WS_AMOUNT, USAGECLASS, USAGETYPE, SERVICECODE,
SERVICECLASS, ZONE_WS, ZONE_RT, NEW_USAGETYPE, IMPACT_CATEGORY_WS, IMPACT_CATEGORY_RT,
NAME ) VALUES ( 
'ALL_RATE', 20000, 2, '19990101', NULL, NULL, NULL, NULL, NULL, NULL, 'MBI', '.*'
, 'TEL', '.*', '.*', '(IN_ROAM|OUT_ROAM)', NULL, 'NAT_MBI', 'NAT_MBI', 'Roaming Mailbox Inquiry'); 
INSERT INTO IFW_USC_MAP ( USC_GROUP, ZONEMODEL, RANK, VALID_FROM, VALID_TO, TIME_FROM,
TIME_TO, QUANTITY_VALUE, MIN_WS_AMOUNT, MAX_WS_AMOUNT, USAGECLASS, USAGETYPE, SERVICECODE,
SERVICECLASS, ZONE_WS, ZONE_RT, NEW_USAGETYPE, IMPACT_CATEGORY_WS, IMPACT_CATEGORY_RT,
NAME ) VALUES ( 
'ALL_RATE', 20000, 4, '19990101', NULL, NULL, NULL, NULL, NULL, NULL, 'CONF', '.*'
, 'TEL', '.*', '.*', '(WORLD.|EUROPE)', NULL, 'WORLD_CONF', 'WORLD_CONF', 'World Conference Call'); 
INSERT INTO IFW_USC_MAP ( USC_GROUP, ZONEMODEL, RANK, VALID_FROM, VALID_TO, TIME_FROM,
TIME_TO, QUANTITY_VALUE, MIN_WS_AMOUNT, MAX_WS_AMOUNT, USAGECLASS, USAGETYPE, SERVICECODE,
SERVICECLASS, ZONE_WS, ZONE_RT, NEW_USAGETYPE, IMPACT_CATEGORY_WS, IMPACT_CATEGORY_RT,
NAME ) VALUES ( 
'ALL_RATE', 20000, 5, '19990101', NULL, NULL, NULL, NULL, NULL, NULL, '.*', '(CORP|CUG)'
, '(TEL|SMS)', '.*', '.*', '(NAT_MOB|NAT_FIX)', NULL, 'NAT_CUG', 'NAT_CUG', 'National Closed-User-Group'); 
INSERT INTO IFW_USC_MAP ( USC_GROUP, ZONEMODEL, RANK, VALID_FROM, VALID_TO, TIME_FROM,
TIME_TO, QUANTITY_VALUE, MIN_WS_AMOUNT, MAX_WS_AMOUNT, USAGECLASS, USAGETYPE, SERVICECODE,
SERVICECLASS, ZONE_WS, ZONE_RT, NEW_USAGETYPE, IMPACT_CATEGORY_WS, IMPACT_CATEGORY_RT,
NAME ) VALUES ( 
'ALL_RATE', 20000, 6, '19990101', NULL, NULL, NULL, NULL, NULL, NULL, '.*', 'FF', '.*'
, '.*', '.*', '(NAT_MOB|NAT_FIX)', NULL, 'NAT_FF', 'NAT_FF', 'National Friends u. Family '); 
INSERT INTO IFW_USC_MAP ( USC_GROUP, ZONEMODEL, RANK, VALID_FROM, VALID_TO, TIME_FROM,
TIME_TO, QUANTITY_VALUE, MIN_WS_AMOUNT, MAX_WS_AMOUNT, USAGECLASS, USAGETYPE, SERVICECODE,
SERVICECLASS, ZONE_WS, ZONE_RT, NEW_USAGETYPE, IMPACT_CATEGORY_WS, IMPACT_CATEGORY_RT,
NAME ) VALUES ( 
'ALL_RATE', 20000, 7, '19990101', NULL, NULL, NULL, NULL, NULL, NULL, '.*', 'HC', 'TEL'
, '.*', '.*', 'NAT_MOB', NULL, 'NAT_FIX', 'NAT_FIX', 'Home-Cell calls to FixNet charges'); 
commit;
 
