INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'HOME', 'Home Records', 1); 
INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'ROAM', 'ROAM Records', 1); 
INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'SUSPR', 'Suspended Records from reprice', 1); 
INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'SUSPB', 'Suspended Records from backout', 1); 
INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'GSMR', 'GSM Roaming Records', 1); 
INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'GPRSR', 'GPRS Roaming Records', 1); 
INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'SUSP', 'Suspended Records', 1); 
INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'OPRT1', 'Operator1 Records', 1); 
INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'OPRT2', 'Operator2 Records', 1); 
INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'SUSPO', 'Suspended Records from outcollect', 1); 
INSERT INTO IFW_SYSTEM_BRAND ( SYSTEM_BRAND, NAME, ACTIVE ) VALUES ( 
'SUSPU', 'Suspended Records from unknown', 1); 

INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'SplitterPipeline', 1,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', 'EUR01', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'HOME'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'TAPOutCollectPipeline', 2,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', 'OPRT2', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'OPRT2'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'SplitterPipeline', 2,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'ROAM'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'TAPOutCollectPipeline', 1,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', 'OPRT1', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'OPRT1'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'TAPOutCollectPipeline', 3,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'SUSP'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'TAPOutSettlementPipeline', 1,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '813', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'GPRSR'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'TAPOutSettlementPipeline', 2,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'GSMR'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'TAPInSettlementPipeline', 1,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '813', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'GPRSR'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'TAPInSettlementPipeline', 2,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'GSMR'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'TAPSettlementBkOutPipeline', 2,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'GSMR'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'TAPSettlementBkOutPipeline', 1,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '813', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'GPRSR'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'PreRecyclePipeline', 1,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', 'TAPOutCollectPipeline', '.*', '.*', '.*', '.*', '.*', '.*', '.*'
, 'SUSPO'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'PreRecyclePipeline', 2,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', 'TAPInRePricePipeline', '.*', '.*', '.*', '.*', '.*', '.*', '.*'
, 'SUSPR'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'PreRecyclePipeline', 3,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', 'TAPSettlementBkOutPipeline', '.*', '.*', '.*', '.*', '.*', '.*'
, '.*', 'SUSPB'); 
INSERT INTO IFW_SPLITTING_TYPE ( PIPELINE, RANK, VALID_FROM, RECORDTYPE, SERVICECODE, USAGECLASS,
SOURCE_NETWORK, DESTIN_NETWORK, SWITCH, TRUNK_IN, TRUNK_OUT, ORIGIN_AREACODE, DESTIN_AREACODE,
TRANSIT_AREACODE, SYSTEM_BRAND ) VALUES ( 
'PreRecyclePipeline', 4,  TO_Date( '01/01/2004 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*', 'SUSPU'); 
COMMIT;
