INSERT INTO IFW_TIMEMODEL ( TIMEMODEL, CODE, NAME ) VALUES ( 
20001, 'NATIONAL', 'National TimeModel'); 
INSERT INTO IFW_TIMEMODEL ( TIMEMODEL, CODE, NAME ) VALUES ( 
20002, 'INTERNAT', 'International TimeModel'); 
INSERT INTO IFW_TIMEMODEL ( TIMEMODEL, CODE, NAME ) VALUES ( 
20003, 'EUROPEAN', 'European TimeModel'); 
INSERT INTO IFW_TIMEMODEL ( TIMEMODEL, CODE, NAME ) VALUES ( 
20004, 'FLAT', 'Flat TimeModel'); 
commit;
 
