INSERT INTO IFW_DISCOUNTRULE ( DISCOUNTRULE, CODE, NAME, DISCOUNTMASTER, 
DRUM_EXPRESSION, RULE_TYPE, DRUM_TYPE ) VALUES ( 
IFW_SEQ_DISCOUNTRULE.NEXTVAL, 'DR10%OFF', 'Discount Rule for Taking 10% Off', (SELECT DISCOUNTMASTER FROM IFW_DISCOUNTMASTER
WHERE CODE ='DA10%OFF'),'TotalQ', '1', 'Q'); 
INSERT INTO IFW_DISCOUNTRULE ( DISCOUNTRULE, CODE, NAME, DISCOUNTMASTER, 
DRUM_EXPRESSION, RULE_TYPE, DRUM_TYPE ) VALUES ( 
IFW_SEQ_DISCOUNTRULE.NEXTVAL, 'DRFMALL', 'Discount Rule for Consuming Free Minutes',(SELECT DISCOUNTMASTER FROM IFW_DISCOUNTMASTER
WHERE CODE ='DAALL'),'TotalQ', '1', 'Q'); 
INSERT INTO IFW_DISCOUNTRULE ( DISCOUNTRULE, CODE, NAME, DISCOUNTMASTER, 
DRUM_EXPRESSION, RULE_TYPE, DRUM_TYPE ) VALUES ( 
IFW_SEQ_DISCOUNTRULE.NEXTVAL, 'CR10%OFF', 'Charging Sharing Rule for Taking 10% Off',(SELECT DISCOUNTMASTER FROM IFW_DISCOUNTMASTER
WHERE CODE ='CA10%OFF'),'TotalC', '1', 'C'); 
commit;
