INSERT INTO IFW_DISCOUNTDETAIL ( DISCOUNTMASTER, RANK, VALID_FROM, VALID_TO,
TIME_FROM, TIME_TO, ZONEMODEL, IMPACT_CATEGORY, SERVICECODE, SERVICECLASS,
TIMEMODEL, TIMEZONE, PRICEMODEL, RESSOURCE, RUM, RECORDTYPE, RATE_PLAN, 
RATE_TAG, GLID ) VALUES ( 
(SELECT DISCOUNTMASTER FROM IFW_DISCOUNTMASTER WHERE CODE ='DA10%OFF'), 1, '19990101', NULL, NULL, NULL, '.*', '.*' , '.*', '.*', '.*',
'.*', '.*', '978', '.*', '.*', '.*', '.*', '.*'); 
INSERT INTO IFW_DISCOUNTDETAIL ( DISCOUNTMASTER, RANK, VALID_FROM, VALID_TO,
TIME_FROM, TIME_TO, ZONEMODEL, IMPACT_CATEGORY, SERVICECODE, SERVICECLASS,
TIMEMODEL, TIMEZONE, PRICEMODEL, RESSOURCE, RUM, RECORDTYPE, RATE_PLAN, 
RATE_TAG, GLID ) VALUES ( 
(SELECT DISCOUNTMASTER FROM IFW_DISCOUNTMASTER WHERE CODE ='DAALL'), 2, '19990101', NULL, NULL, NULL, '.*', '.*' , '.*', '.*', '.*',
'.*', '.*', '.*', '.*', '.*', '.*', '.*', '.*'); 
INSERT INTO IFW_DISCOUNTDETAIL ( DISCOUNTMASTER, RANK, VALID_FROM, VALID_TO,
TIME_FROM, TIME_TO, ZONEMODEL, IMPACT_CATEGORY, SERVICECODE, SERVICECLASS,
TIMEMODEL, TIMEZONE, PRICEMODEL, RESSOURCE, RUM, RECORDTYPE, RATE_PLAN, 
RATE_TAG, GLID ) VALUES ( 
(SELECT DISCOUNTMASTER FROM IFW_DISCOUNTMASTER WHERE CODE ='CA10%OFF'), 3, '20030101', NULL, NULL, NULL, '.*', '.*' , '.*', '.*', '.*',
'.*', '.*', '978', '.*', '.*', '.*', '.*', '.*'); 
commit;
 
