INSERT INTO IFW_APN_MAP ( APN_GROUP, RANK, SERVICECODE, ACCESSPOINTNAME, ZONE_WS, ZONE_RT,
PDP_ADDRESS, NEW_ZONE_WS, NEW_ZONE_RT ) VALUES ( 
'ALL_RATE', 1, 'GPR.*', '(.*\.portal.com|.*\.de)', '.*', '.*', '.*', 'NAT_MOB', 'NAT_MOB'); 
INSERT INTO IFW_APN_MAP ( APN_GROUP, RANK, SERVICECODE, ACCESSPOINTNAME, ZONE_WS, ZONE_RT,
PDP_ADDRESS, NEW_ZONE_WS, NEW_ZONE_RT ) VALUES ( 
'ALL_RATE', 2, 'GPR.*', 'free.net.com', '.*', '.*', '.*', 'FREE', 'FREE'); 
INSERT INTO IFW_APN_MAP ( APN_GROUP, RANK, SERVICECODE, ACCESSPOINTNAME, ZONE_WS, ZONE_RT,
PDP_ADDRESS, NEW_ZONE_WS, NEW_ZONE_RT ) VALUES ( 
'ALL_RATE', 3, 'GPR.*', '.*\.ibm.com', '.*', 'NAT_.*', '.*', 'NAT_FIX', 'NAT_FIX'); 
INSERT INTO IFW_APN_MAP ( APN_GROUP, RANK, SERVICECODE, ACCESSPOINTNAME, ZONE_WS, ZONE_RT,
PDP_ADDRESS, NEW_ZONE_WS, NEW_ZONE_RT ) VALUES ( 
'ALL_RATE', 4, 'GPR.*', '.*\.com', '.*', '!(NAT.*|EUROPE)', '.*', 'WORLD1', 'WORLD1'); 
INSERT INTO IFW_APN_MAP ( APN_GROUP, RANK, SERVICECODE, ACCESSPOINTNAME, ZONE_WS, ZONE_RT,
PDP_ADDRESS, NEW_ZONE_WS, NEW_ZONE_RT ) VALUES ( 
'ALL_RATE', 99, 'GPR.*', '.*', '.*', 'NAT_.*', '.*', 'NAT_MOB', 'NAT_MOB'); 
INSERT INTO IFW_APN_MAP ( APN_GROUP, RANK, SERVICECODE, ACCESSPOINTNAME, ZONE_WS, ZONE_RT,
PDP_ADDRESS, NEW_ZONE_WS, NEW_ZONE_RT ) VALUES ( 
'ALL_RATE', 100, 'GPR.*', '.*', '.*', '.*', '.*', 'WORLD2', 'WORLD2'); 
INSERT INTO IFW_APN_MAP ( APN_GROUP, RANK, SERVICECODE, ACCESSPOINTNAME, ZONE_WS, ZONE_RT,
PDP_ADDRESS, NEW_ZONE_WS, NEW_ZONE_RT ) VALUES ( 
'ALL_RATE', 5, 'GPR.*', 'wap..*', '.*', '(NAT_MOB|NAT_FIX)', '.*', 'NAT_FIX', 'NAT_FIX'); 
commit;
 
