INSERT INTO IFW_DISCOUNTMASTER ( DISCOUNTMASTER, CODE, NAME ) VALUES ( 
IFW_SEQ_DISCOUNTMASTER.NEXTVAL, 'DA10%OFF', 'Discount Master For Taking 10% Off'); 
INSERT INTO IFW_DISCOUNTMASTER ( DISCOUNTMASTER, CODE, NAME ) VALUES ( 
IFW_SEQ_DISCOUNTMASTER.NEXTVAL, 'DAALL', 'Discount Master For All services'); 
INSERT INTO IFW_DISCOUNTMASTER ( DISCOUNTMASTER, CODE, NAME ) VALUES ( 
IFW_SEQ_DISCOUNTMASTER.NEXTVAL, 'CA10%OFF', 'Charge Share Master For Taking 10% Off'); 
commit;
 
