@ifw_edrc_desc.sql
@ifw_edrc_field.sql
@ifw_alias_map.sql
@ifw_calendar.sql
@ifw_holiday.sql
@ifw_destinationdesc.sql
@ifw_pipeline.sql
@ifw_uom.sql
@ifw_resource.sql
@ifw_exchange_rate.sql
@ifw_taxcode.sql
@ifw_taxgroup.sql
@ifw_tax.sql
@ifw_glaccount.sql
@ifw_service.sql
@ifw_serviceclass.sql
@ifw_ref_map.sql
@ifw_map_group.sql
@ifw_servicecode_map.sql
@ifw_usageclass.sql
@ifw_usageclass_map.sql
@ifw_usc_group.sql
@ifw_rsc_group.sql
@ifw_apn_group.sql
@ifw_zonemodel.sql
@ifw_impact_category.sql
@ifw_standard_zone.sql
@ifw_usagetype.sql
@ifw_usagescenario_map.sql
@ifw_apn_map.sql
@ifw_discarding.sql
@ifw_daycode.sql
@ifw_timeinterval.sql
@ifw_timezone.sql
@ifw_timemodel.sql
@ifw_timemodel_lnk.sql
@ifw_pricemodel.sql
@ifw_pricemodel_step.sql
@ifw_discountmodel.sql
@ifw_discountmdl_ver.sql
@ifw_discountmaster.sql
@ifw_discountdetail.sql
@ifw_discounttrigger.sql
@ifw_discountcondition.sql
@ifw_discountrule.sql
@ifw_discountstep.sql
@ifw_discountbalimpact.sql
@ifw_discountmdl_cnf.sql
@ifw_rateplan.sql
@ifw_rateplan_ver.sql
@ifw_rateplan_cnf.sql
@ifw_specialdayrate.sql
@ifw_specialday_lnk.sql
@ifw_networkoper.sql
@ifw_networkmodel.sql
@ifw_icproduct_all.sql
@ifw_splittingtype_all.sql
@ifw_seqcheck.sql
exit
