DROP TABLE TD_GL_REPORT_T;

CREATE TABLE TD_GL_REPORT_T
(
  REPORT_NAME       CHAR(255 BYTE),
  BILL_CYCLE        VARCHAR2(100 BYTE),
  CUSTOMER_TYPE     VARCHAR2(1023 BYTE),
  TEST_ACCOUNT      VARCHAR2(10),
  BILL_CYCLE_START  VARCHAR2(40 BYTE),
  BILL_CYCLE_END    VARCHAR2(40 BYTE),
  GL_ID             INTEGER,
  DESCR             VARCHAR2(255 BYTE),
  TAX_CODE          VARCHAR2(255 BYTE),
  AMOUNT            NUMBER,
  COUNT               NUMBER
);



DROP TABLE td_gl_reports_exec_logs_t;

create table td_gl_reports_exec_logs_t
(created_t date,
report_name varchar2(255),
ledger_poid number,
START_T  VARCHAR2(40 BYTE),
END_T    VARCHAR2(40 BYTE));



DROP TABLE TD_GL_PREPAID_REPORT_T;

CREATE TABLE TD_GL_PREPAID_REPORT_T
(
  REPORT_NAME       CHAR(50 BYTE),
  BILL_CYCLE        VARCHAR2(50 BYTE),
  CUSTOMER_TYPE     VARCHAR2(1023 BYTE),
  TEST_ACCOUNT      VARCHAR2(10),
  BILL_CYCLE_START  VARCHAR2(50 BYTE),
  BILL_CYCLE_END    VARCHAR2(50 BYTE),
  GL_ID             INTEGER,
  DESCR             VARCHAR2(255 BYTE),
  TAX_CODE          VARCHAR2(255 BYTE),
  AMOUNT            NUMBER,
  COUNT               NUMBER
);




DROP TABLE TD_GL_UNBILLED_REPORT_T;

CREATE TABLE TD_GL_UNBILLED_REPORT_T
(
  REPORT_NAME       CHAR(50 BYTE),
  BILL_CYCLE        VARCHAR2(50 BYTE),
  CUSTOMER_TYPE     VARCHAR2(1023 BYTE),
  TEST_ACCOUNT      VARCHAR2(10),
  BILL_CYCLE_START  VARCHAR2(50 BYTE),
  BILL_CYCLE_END    VARCHAR2(50 BYTE),
  GL_ID             INTEGER,
  DESCR             VARCHAR2(255 BYTE),
  COUNT               NUMBER,
  TAX_CODE          VARCHAR2(255 BYTE),
  UNBILLED_EARNED    NUMBER,
  UNBILLED_UNEARNED      NUMBER
);

