#define TD_FLD_TGEO_ID		PIN_MAKE_FLD(PIN_FLDT_STR, 10000)		/* IN Field TGEO_ID */
#define TD_FLD_CDR_TYPE		PIN_MAKE_FLD(PIN_FLDT_INT, 10001)		/* CDRType */
#define TD_FLD_CUSTOM_DATA_INFO		PIN_MAKE_FLD(PIN_FLDT_SUBSTRUCT, 10002)		/* DATA_INFO */
#define TD_FLD_SEQUENCE_NUMBER		PIN_MAKE_FLD(PIN_FLDT_STR, 10003)		/* SEQUENCE_NUMBER */
#define TD_FLD_ACCOUNT_TYPE		PIN_MAKE_FLD(PIN_FLDT_STR, 10004)		/* ACCOUNT_TYPE */
#define TD_FLD_CASH_AMOUNT_QUANTITY		PIN_MAKE_FLD(PIN_FLDT_DECIMAL, 10005)		/* CASH_AMOUNT_QUANTITY */
#define TD_FLD_BUNDLE_AMOUNT_QUANTITY		PIN_MAKE_FLD(PIN_FLDT_DECIMAL, 10006)		/* BUNDLE_AMOUNT_QUANTITY */
#define TD_FLD_ORIGINATING_COUNTRY		PIN_MAKE_FLD(PIN_FLDT_STR, 10007)		/* ORIGINATING_COUNTRY */
#define TD_FLD_ORIGINATING_ZONE		PIN_MAKE_FLD(PIN_FLDT_STR, 10008)		/* ORIGINATING_ZONE */
#define TD_FLD_DESTINATION_COUNTRY		PIN_MAKE_FLD(PIN_FLDT_STR, 10009)		/* DESTINATION _COUNTRY */
#define TD_FLD_DESTINATION_ZONE		PIN_MAKE_FLD(PIN_FLDT_STR, 10010)		/* DESTINATION _ZONE */
#define TD_FLD_CASCADE_ID		PIN_MAKE_FLD(PIN_FLDT_INT, 10011)		/* CASCADE_ID */
#define TD_FLD_END_CALL_REASON		PIN_MAKE_FLD(PIN_FLDT_INT, 10012)		/* END_CALL_REASON */
#define TD_FLD_RATING_GROUP_CODE		PIN_MAKE_FLD(PIN_FLDT_STR, 10013)		/* RATING_GROUP_CODE */
#define TD_FLD_RATING_GROUP_TYPE		PIN_MAKE_FLD(PIN_FLDT_STR, 10014)		/* RATING_GROUP_TYPE */
#define TD_FLD_RATES		PIN_MAKE_FLD(PIN_FLDT_DECIMAL, 10015)		/* RATES */
#define TD_FLD_MFILE		PIN_MAKE_FLD(PIN_FLDT_STR, 10016)		/* MFILE */
#define TD_FLD_IN_PACKAGE_CODE		PIN_MAKE_FLD(PIN_FLDT_STR, 10017)		/* IN_PACKAGE_CODE */
#define TD_FLD_PRODUCT		PIN_MAKE_FLD(PIN_FLDT_STR, 10018)		/* PRODUCT */
#define TD_FLD_SHARERS_MSISDN		PIN_MAKE_FLD(PIN_FLDT_STR, 10019)		/* SHARERS_MSISDN */
#define TD_FLD_SHARERS_PRODUCT		PIN_MAKE_FLD(PIN_FLDT_STR, 10020)		/* SHARERS_PRODUCT */
#define TD_FLD_SHRD		PIN_MAKE_FLD(PIN_FLDT_STR, 10021)		/* SHRD */
#define TD_FLD_SCP_ID		PIN_MAKE_FLD(PIN_FLDT_INT, 10022)		/* SCP_ID */
#define TD_FLD_RECORD_DATE		PIN_MAKE_FLD(PIN_FLDT_TSTAMP, 10023)		/* RECORD_DATE */
#define TD_FLD_ACCT_ID		PIN_MAKE_FLD(PIN_FLDT_INT, 10024)		/* ACCT_ID */
#define TD_FLD_ACCT_REF_ID		PIN_MAKE_FLD(PIN_FLDT_INT, 10025)		/* ACCT_REF_ID */
#define TD_FLD_CLI		PIN_MAKE_FLD(PIN_FLDT_STR, 10026)		/* CLI */
#define TD_FLD_OGEO_ID		PIN_MAKE_FLD(PIN_FLDT_INT, 10027)		/* OGEO_ID */
#define TD_FLD_OVERRIDDEN_TARIFF_PLAN		PIN_MAKE_FLD(PIN_FLDT_INT, 10028)		/* OVERRIDDEN_TARIFF_PLAN */
#define TD_FLD_CS		PIN_MAKE_FLD(PIN_FLDT_STR, 10029)		/* CS */
#define TD_FLD_DISCOUNT_TYPE		PIN_MAKE_FLD(PIN_FLDT_STR, 10030)		/* DISCOUNT_TYPE */
#define TD_FLD_MULTIPLIER		PIN_MAKE_FLD(PIN_FLDT_STR, 10031)		/* MULTIPLIER */
#define TD_FLD_OPROD		PIN_MAKE_FLD(PIN_FLDT_STR, 10032)		/* OPROD */
#define TD_FLD_UMS		PIN_MAKE_FLD(PIN_FLDT_STR, 10033)		/* UMS */
#define TD_FLD_UPROD		PIN_MAKE_FLD(PIN_FLDT_STR, 10034)		/* UPROD */
#define TD_FLD_CUSTOM_SMS_INFO		PIN_MAKE_FLD(PIN_FLDT_SUBSTRUCT, 10035)		/* CUSTOM_SMS_INFO */
#define TD_FLD_EVENT_CLASS		PIN_MAKE_FLD(PIN_FLDT_ARRAY, 10036)		/* EVENT_CLASS */
#define TD_FLD_EVENTS_CLASS		PIN_MAKE_FLD(PIN_FLDT_STR, 10037)		/* EVENT_CLASS */
#define TD_FLD_EVENT_NAME		PIN_MAKE_FLD(PIN_FLDT_STR, 10038)		/* EVENT_NAME */
#define TD_FLD_EVENT_COST		PIN_MAKE_FLD(PIN_FLDT_STR, 10039)		/* EVENT_COST */
#define TD_FLD_EVENT_TIME_COST		PIN_MAKE_FLD(PIN_FLDT_STR, 10040)		/* EVENT_TIME_COST */
#define TD_FLD_EVENT_DATA_COST		PIN_MAKE_FLD(PIN_FLDT_STR, 10041)		/* EVENT_DATA_COST */
#define TD_FLD_EVENT_UNIT_COST		PIN_MAKE_FLD(PIN_FLDT_STR, 10042)		/* EVENT_UNIT_COST */
#define TD_FLD_CASCADE		PIN_MAKE_FLD(PIN_FLDT_STR, 10043)		/* CASCADE */
#define TD_FLD_PROD_CAT_ID		PIN_MAKE_FLD(PIN_FLDT_STR, 10044)		/* PROD_CAT_ID */
#define TD_FLD_CUSTOM_VP_INFO		PIN_MAKE_FLD(PIN_FLDT_SUBSTRUCT, 10045)		/* CUSTOM_VP_INFO */
#define TD_FLD_EXT1		PIN_MAKE_FLD(PIN_FLDT_INT, 10046)		/* EXT1 */
#define TD_FLD_EXT2		PIN_MAKE_FLD(PIN_FLDT_INT, 10047)		/* EXT2 */
#define TD_FLD_EXT4		PIN_MAKE_FLD(PIN_FLDT_INT, 10048)		/* EXT4 */
#define TD_FLD_CHARGE_EXPIRY		PIN_MAKE_FLD(PIN_FLDT_TSTAMP, 10049)		/* CHARGE_EXPIRY */
#define TD_FLD_CHARGE_NAME		PIN_MAKE_FLD(PIN_FLDT_STR, 10050)		/* CHARGE_NAME */
#define TD_FLD_NEW_ACCT_EXPIRY		PIN_MAKE_FLD(PIN_FLDT_TSTAMP, 10051)		/* NEW_ACCT_EXPIRY */
#define TD_FLD_NEW_BALANCE_EXPIRIES		PIN_MAKE_FLD(PIN_FLDT_STR, 10052)		/* NEW_BALANCE_EXPIRIES */
#define TD_FLD_NEW_CHARGE_STATE		PIN_MAKE_FLD(PIN_FLDT_STR, 10053)		/* NEW_CHARGE_STATE */
#define TD_FLD_OLD_ACCT_EXPIRY		PIN_MAKE_FLD(PIN_FLDT_TSTAMP, 10054)		/* OLD_ACCT_EXPIRY */
#define TD_FLD_OLD_BALANCE_EXPIRIES		PIN_MAKE_FLD(PIN_FLDT_STR, 10055)		/* OLD_BALANCE_EXPIRIES */
#define TD_FLD_OLD_CHARGE_EXPIRY		PIN_MAKE_FLD(PIN_FLDT_TSTAMP, 10056)		/* OLD_CHARGE_EXPIRY */
#define TD_FLD_OLD_CHARGE_STATE		PIN_MAKE_FLD(PIN_FLDT_STR, 10057)		/* OLD_CHARGE_STATE */
#define TD_FLD_PARTNER		PIN_MAKE_FLD(PIN_FLDT_STR, 10058)		/* PARTNER */
#define TD_FLD_PAYMENT		PIN_MAKE_FLD(PIN_FLDT_STR, 10059)		/* PAYMENT */
#define TD_FLD_REFERENCE		PIN_MAKE_FLD(PIN_FLDT_STR, 10060)		/* REFERENCE */
#define TD_FLD_RESULT		PIN_MAKE_FLD(PIN_FLDT_STR, 10061)		/* RESULT */
#define TD_FLD_TX_ID		PIN_MAKE_FLD(PIN_FLDT_STR, 10062)		/* TX_ID */
#define TD_FLD_VOUCHER_TYPE		PIN_MAKE_FLD(PIN_FLDT_STR, 10063)		/* VOUCHER_TYPE */
#define TD_FLD_CUSTOM_VOICE_INFO		PIN_MAKE_FLD(PIN_FLDT_SUBSTRUCT, 10064)		/* CUSTOM_VOICE_INFO */
#define TD_FLD_CELL_ID		PIN_MAKE_FLD(PIN_FLDT_STR, 10065)		/* CELL_ID */
#define TD_FLD_SK		PIN_MAKE_FLD(PIN_FLDT_STR, 10066)		/* SK */
#define TD_FLD_LOC_NUM		PIN_MAKE_FLD(PIN_FLDT_STR, 10067)		/* LOC_NUM */
#define TD_FLD_CALL_ID		PIN_MAKE_FLD(PIN_FLDT_STR, 10068)		/* CALL_ID */
#define TD_FLD_RDPN		PIN_MAKE_FLD(PIN_FLDT_STR, 10069)		/* RDPN */
#define TD_FLD_TN		PIN_MAKE_FLD(PIN_FLDT_STR, 10070)		/* TN */
#define PIN_FLD_API_BAL_IMPACTS               PIN_MAKE_FLD(PIN_FLDT_ARRAY, 10077)               /* API_BAL_IMPACTS */
#define PIN_FLD_PARTNER_INFO    		PIN_MAKE_FLD(PIN_FLDT_ARRAY, 10078)               /* PARTNER_INFO PAY_TYPE */
#define PIN_FLD_PARTNER_ACCOUNT_NO    	PIN_MAKE_FLD(PIN_FLDT_STR, 10079)               /* PARTNER ACCOUNT NO */
#define PIN_FLD_FS_INFO    		PIN_MAKE_FLD(PIN_FLDT_ARRAY, 10080)               /* FS_INFO PAY_TYPE */
#define PIN_FLD_FS_ACCOUNT_NO    	PIN_MAKE_FLD(PIN_FLDT_STR, 10081)               /* FS ACCOUNT NO */
#define PIN_FLD_FS_ACCOUNT_NAME    	PIN_MAKE_FLD(PIN_FLDT_STR, 10082)               /* FS ACCOUNT NAME */
