UNRECOVERABLE

LOAD DATA
CHARACTERSET UTF8
TRUNCATE
INTO TABLE TMP_PROF290957164989291301
SINGLEROW
FIELDS TERMINATED BY X'09'
(
  RECORD_TYPE                           FILLER, -- Not loaded
  RECORD_NUMBER                         FILLER, -- Not loaded
  BAL_GRP_OBJ_DB                        INTEGER EXTERNAL TERMINATED BY X'20',
  BAL_GRP_OBJ_TYPE                      CHAR TERMINATED BY X'20',
  BAL_GRP_OBJ_ID0                       INTEGER EXTERNAL TERMINATED BY X'20',
  BAL_GRP_OBJ_REV                       INTEGER EXTERNAL,
  CRITERIA_NAME                         CHAR,
  LAST_EVENT_PROCESS_T                  INTEGER EXTERNAL,
  BILL_CYCLE_T                          INTEGER EXTERNAL,
  PROFILE_OBJ_DB                        INTEGER EXTERNAL TERMINATED BY X'20',
  PROFILE_OBJ_TYPE                      CHAR TERMINATED BY X'20',
  PROFILE_OBJ_ID0                       INTEGER EXTERNAL TERMINATED BY X'20',
  PROFILE_OBJ_REV                       INTEGER EXTERNAL,

  -- Fields generated by REL
  OBJ_ID0                               INTEGER EXTERNAL,
  REC_ID                                INTEGER EXTERNAL
)
