select distinct TD.POID_ID0 ||',11_944'
from
  PIN.TD_USGEVENT_DETAILS TD,
  PIN.ITEM_T IT,
  PIN.PURCHASED_PRODUCT_T PROD,
  PIN.EVENT_T ET
where
    TD.POID_TYPE = '/event/delayed/session/telco/gsm/valuepack'
and TD.DESCR='Roaming Data Add-on'
and IT.POID_ID0 = TD.ITEM_POID_ID0
and IT.SERVICE_OBJ_ID0 = PROD.SERVICE_OBJ_ID0
and ET.POID_ID0 = TD.EVENT_POID_ID0
AND ET.START_T > PROD.CREATED_T
and PROD.PRODUCT_OBJ_ID0 in (1672114294,1672117878);