/*	
 *	@(#)%Portal Version: subscription.h:CommonIncludeInt:34:2008-Jun-29 23:50:21 %
 *	
* Copyright (c) 1996, 2011, Oracle and/or its affiliates. All rights reserved. 
 *	
 *	This material is the confidential property of Oracle Corporation or its
 *	licensors and may be used, reproduced, stored or transmitted only in
 *	accordance with a valid Oracle license or sublicense agreement.
 */

#ifndef _PCM_SUBSCRIPTION_OPS_H_
#define _PCM_SUBSCRIPTION_OPS_H_

/*
 * This file contains the opcode definitions for the Billing PCM API.
 */

/* 
   NAME: TOTAL RANGE; USED RANGE; RESERVED RANGE; ASSOCIATED FM (if any)
   =====================================================================
   PCM_SUBSCRIPTION_OPS:     3751..3775,9061..9100;3751..3775,9061..9073;9074..9100; 
				fm_subscription

   PCM_SUBSCRIPTION_POL_OPS: 3776..3800; 3776..3790 ; 3791..3800; 
				fm_subscription_pol
 */

#include "ops/base.h"

	/*
	 * Opcodes for Subscription Management Standard FM (3751 - 3775) and (9061 - 9100)
	 */
#define PCM_OP_SUBSCRIPTION_PURCHASE_DISCOUNT		3751
#define PCM_OP_SUBSCRIPTION_CANCEL_DISCOUNT		3752
#define PCM_OP_SUBSCRIPTION_SET_DISCOUNTINFO		3753
#define PCM_OP_SUBSCRIPTION_SET_DISCOUNT_STATUS		3754
#define PCM_OP_SUBSCRIPTION_CYCLE_ROLLOVER     		3755
#define PCM_OP_SUBSCRIPTION_CYCLE_DISCOUNT     		3756
#define PCM_OP_SUBSCRIPTION_SHARING_GROUP_CREATE	3757
#define PCM_OP_SUBSCRIPTION_SHARING_GROUP_MODIFY	3758
#define PCM_OP_SUBSCRIPTION_SHARING_GROUP_DELETE	3759
#define PCM_OP_SUBSCRIPTION_SHARING_GROUP_SET_PARENT    3760
#define PCM_OP_SUBSCRIPTION_ORDERED_BALGRP      	3761
#define PCM_OP_SUBSCRIPTION_SET_MAPPING_TABLE      	3762
#define PCM_OP_SUBSCRIPTION_TRANSFER_SUBSCRIPTION      	3763
#define PCM_OP_SUBSCRIPTION_CANCEL_SUBSCRIPTION      	3764
#define PCM_OP_SUBSCRIPTION_RATE_CHANGE		      	3765

/*
Moved PCM_OP_SUBSCRIPTION_INSERT_RERATE_REQUEST opcode
to PCM_OP_RERATE_INSERT_RERATE_REQUEST.
Using same opcode number as before.
*/
#define PCM_OP_SUBSCRIPTION_INSERT_RERATE_REQUEST      	3766	/*PCM_OBSOLETE*/

#define PCM_OP_SUBSCRIPTION_VALIDATE_DISCOUNT_DEPENDENCY	3767
#define PCM_OP_SUBSCRIPTION_PREP_RATE_CHANGE		3768
#define PCM_OP_SUBSCRIPTION_ORDERED_BALGRP_BULK_MODIFY	3769
#define PCM_OP_SUBSCRIPTION_MONITORS_UPDATE		3770
#define PCM_OP_SUBSCRIPTION_VALIDATE_MONITOR_MEMBERS    3771
#define PCM_OP_SUBSCRIPTION_DISCOUNT_ANALYSIS		3772
#define PCM_OP_SUBSCRIPTION_COUNT_LINES			3773	/*PCM_OBSOLETE*/
#define PCM_OP_SUBSCRIPTION_COUNT_SUBSCRIPTIONS		3773
#define PCM_OP_SUBSCRIPTION_NOTIFY_AGGREGATION          3774
#define PCM_OP_SUBSCRIPTION_UPDATE_CDC			3775
#define PCM_OP_SUBSCRIPTION_UPDATE_SUBSCRIPTION_COUNT   9061
#define PCM_OP_SUBSCRIPTION_GET_PURCHASED_OFFERINGS   	9062
#define PCM_OP_SUBSCRIPTION_CALC_BEST_PRICING   	9063
#define PCM_OP_SUBSCRIPTION_CALCULATE_VALIDITY		9064
#define PCM_OP_SUBSCRIPTION_SET_VALIDITY		9065
#define PCM_OP_SUBSCRIPTION_PROVISION_ERA		9066
#define PCM_OP_SUBSCRIPTION_SET_VALIDITY_FROM_STRING	9067
#define PCM_OP_SUBSCRIPTION_APPLY_RATE			9068
#define PCM_OP_SUBSCRIPTION_TRANSFER_ROLLOVER		9069
#define PCM_OP_SUBSCRIPTION_GET_ACTG_DATES		9070
#define PCM_OP_SUBSCRIPTION_RERATE_NOTIFY_CYCLE		9071
#define PCM_OP_SUBSCRIPTION_SET_BUNDLE			9072
#define PCM_OP_SUBSCRIPTION_SERVICE_BALGRP_TRANSFER	9073

	/* reserve 9074- 9100 */

	/*
	 * Opcodes for Subscription Management Policy FM (3776 - 3800)
	 */
#define PCM_OP_SUBSCRIPTION_POL_SPEC_CANCEL_DISCOUNT	3776
#define PCM_OP_SUBSCRIPTION_POL_SNOWBALL_DISCOUNT	3777
#define PCM_OP_SUBSCRIPTION_POL_GET_SPONSORS     	3778
#define PCM_OP_SUBSCRIPTION_POL_SPEC_FOLD        	3779
#define PCM_OP_SUBSCRIPTION_POL_SPEC_RERATE        	3780
#define PCM_OP_SUBSCRIPTION_POL_PREP_FOLD        	3781
#define PCM_OP_SUBSCRIPTION_POL_PREP_MEMBERS        	3782
#define PCM_OP_SUBSCRIPTION_POL_COUNT_LINES		3783	/*PCM_OBSOLETE*/
#define PCM_OP_SUBSCRIPTION_POL_COUNT_SUBSCRIPTIONS	3783
#define PCM_OP_SUBSCRIPTION_POL_NOTIFY_AGGREGATION      3784
#define PCM_OP_SUBSCRIPTION_POL_UPDATE_CDC		3785
#define PCM_OP_SUBSCRIPTION_POL_UPDATE_SUBSCRIPTION_COUNT   3786
#define PCM_OP_SUBSCRIPTION_POL_GENERATE_RERATE_REQUEST   3787
#define PCM_OP_SUBSCRIPTION_POL_AUTO_SUBSCRIBE_MEMBERS   3788
#define PCM_OP_SUBSCRIPTION_POL_AUTO_SUBSCRIBE_SERVICE   3789
#define PCM_OP_SUBSCRIPTION_POL_POST_TRANSFER_SUBSCRIPTION   3790

	/* reserve 3791 - 3800 */


#endif /* _PCM_SUBSCRIPTION_OPS_H_ */

